Repository apache/gravitino, pull requests merged in 2023-12, with the labels that each got.

#1126 [Minor] Minor formating and changes to fit with the style guide.
  docs/apache-hive-catalog.md
  docs/docker-image-details.md
  docs/gravitino-server-config.md
  docs/how-to-sign-releases.md
  docs/how-to-test.md
  docs/iceberg-rest-service.md
  docs/index.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/metrics.md
  docs/overview.md
  docs/security.md
Labels: need backport, branch-0.3

#1128 [MINOR] fix(docs): Fix the wrong link in the `README.md`
  README.md
Labels: need backport, branch-0.3

#1131 [MINOR] docs(lakehouse-iceberg): improvement lakehouse iceberg document
  docs/apache-hive-catalog.md
  docs/iceberg-rest-service.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
Labels: need backport, branch-0.3

#1137 [#1136] improvement(docs): Add the `md` suffix for every link in the markdown
  docs/apache-hive-catalog.md
  docs/getting-started.md
  docs/gravitino-server-config.md
  docs/how-to-install.md
  docs/how-to-test.md
  docs/iceberg-rest-service.md
  docs/index.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/publish-docker-images.md
  docs/security.md
  docs/trino-connector/catalog-hive.md
  docs/trino-connector/catalog-iceberg.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
  docs/trino-connector/index.md
  docs/trino-connector/installation.md
  docs/trino-connector/supported-catalog.md
  docs/trino-connector/trino-connector.md
Labels: need backport, branch-0.3

#1139 [Minor] improvement(docs): Optimized Trino related docs.
  docs/lakehouse-iceberg-catalog.md
  docs/trino-connector/catalog-hive.md
  docs/trino-connector/catalog-iceberg.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
  docs/trino-connector/configuration.md
  docs/trino-connector/installation.md
  docs/trino-connector/supported-catalog.md
  docs/trino-connector/trino-connector.md
Labels: need backport, branch-0.3

#1146 [MINOR] fix(docs): fix ./gradlew spotlessApply of Coding standards
  CONTRIBUTING.md
Labels: need backport

#1147 [MINOR] fix(docs): Fix link of REST API page
  docs/index.md
Labels: need backport, branch-0.3

#1145 [#1052] fix(common): position name should support upper-case when add a column
  common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
  common/src/test/java/com/datastrato/gravitino/dto/requests/TestTableUpdatesRequest.java
Labels: need backport, branch-0.3

#1152 [Minor] improvement(docs): Optimize Trino related docs and fix some minor mistakes in docs
  docs/trino-connector/configuration.md
  docs/trino-connector/supported-catalog.md
Labels: need backport, branch-0.3

#1170 [#1166] fix(docs): Fix typos `graviton` and syntax problems in docs
  docs/how-to-test.md
  docs/iceberg-rest-service.md
  docs/index.md
Labels: need backport, branch-0.3

#1177 [#1154] fix(trino-connector): Fix the issue with joins causing errors in PostgreSQL.
  integration-test/src/test/resources/trino-queries/catalogs/jdbc-postgresql/00003_join_pushdown.sql
  integration-test/src/test/resources/trino-queries/catalogs/jdbc-postgresql/00003_join_pushdown.txt
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitManager.java
Labels: need backport, branch-0.3

#1163 [#1047] improvement(core): Fix the issue of StringIdentifier in metalake property
  common/src/main/java/com/datastrato/gravitino/dto/MetalakeDTO.java
  core/src/main/java/com/datastrato/gravitino/StringIdentifier.java
  core/src/main/java/com/datastrato/gravitino/meta/BaseMetalake.java
  core/src/main/java/com/datastrato/gravitino/meta/MetalakeManager.java
  core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java
  core/src/test/java/com/datastrato/gravitino/meta/TestMetalakeManager.java
Labels: need backport, branch-0.3

#1189 [MINOR] fix(docs): Fix a typo
  docs/security.md
Labels: need backport, branch-0.3

#1183 [#1171] bugfix(postgresql): Fix bug where the same table name can be loaded under multiple schemas.
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/TestPostgreSqlTableOperations.java
Labels: need backport, branch-0.3

#1214 [MINOR] fix(docs): Modify the required value for the document `security.md`
  docs/security.md
Labels: need backport, branch-0.3

#1228 [MINOR] fix(doc): Fix a JSON format error in doc manage-metadata-using-gravitino.md
  docs/manage-metadata-using-gravitino.md
Labels: need backport, branch-0.3

#1211 [#879][#925] Docker network Pool overlaps with other one on this address space
  dev/docker/tools/docker-connector.conf
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/BaseContainer.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/NetworksConflictTest.java
Labels: need backport, branch-0.3

#1236 [Minor] docs: Add more details about dropping schema and tables
  docs/manage-metadata-using-gravitino.md
Labels: need backport, branch-0.3

#1243 [MINOR] fix(docs): Modify the document according to the README of playground
  docs/how-to-use-the-playground.md
Labels: need backport, branch-0.3

#1235 [#1231] Fix bugs in drop MySQL schemas
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestJdbcAbstractIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java
Labels: need backport, branch-0.3

#1257 [#1253] bugfix(jdbc): fix jdbc catalog store empty audit info issue
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  core/src/main/java/com/datastrato/gravitino/StringIdentifier.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogOperationDispatcher.java
  core/src/main/java/com/datastrato/gravitino/meta/BaseMetalake.java
  core/src/main/java/com/datastrato/gravitino/meta/MetalakeManager.java
  core/src/test/java/com/datastrato/gravitino/TestStringIdentifier.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Labels: bug, need backport, branch-0.3

#1265 [Minor] Improve English, use better names and data, simplify SQL
  docs/how-to-use-the-playground.md
Labels: need backport, branch-0.3

#1270 [#1469] improvement(doc): Add doc about webUI operation
  docs/assets/webui/create-catalog.png
  docs/assets/webui/create-metalake-dialog.png
  docs/assets/webui/created-catalog.png
  docs/assets/webui/delete-metalake.png
  docs/assets/webui/demo-columns.png
  docs/assets/webui/demo-tables.png
  docs/assets/webui/login-with-oauth.png
  docs/assets/webui/metalake-actions.png
  docs/assets/webui/metalake-catalogs-details.png
  docs/assets/webui/metalake-catalogs.png
  docs/assets/webui/metalake-details.png
  docs/assets/webui/metalake-list.png
  docs/assets/webui/metalakes-oauth.png
  docs/assets/webui/metalakes-simple.png
  docs/assets/webui/props-hive.png
  docs/assets/webui/props-iceberg-hive.png
  docs/assets/webui/props-iceberg-jdbc.png
  docs/assets/webui/props-mysql.png
  docs/assets/webui/props-pg.png
  docs/webui.md
Labels: need backport, branch-0.3
