Repository apache/gravitino, pull requests merged in 2024-08, with the labels that each got.

#4250 [#4264] feat(iceberg): support access S3 with static access key for Iceberg REST server and Gravitino Iceberg catalog
  catalogs/catalog-common/build.gradle.kts
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
  common/src/main/java/org/apache/gravitino/utils/MapUtils.java
  conf/gravitino-iceberg-rest-server.conf.template
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  gradle/libs.versions.toml
  iceberg/iceberg-common/build.gradle.kts
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergTableOps.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java
  iceberg/iceberg-common/src/test/java/org/apache/gravitino/iceberg/common/utils/TestIcebergCatalogUtil.java
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java
Labels: ICEBERG-REST-SERVER

#4340 [HOTFIX] fix spotless check error
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
Labels: branch-0.5

#4341 [MINOR] CI: Add auto cherry-pick to branch-0.6 and remove self token
  .github/workflows/auto-cherry-pick.yml
Labels: branch-0.5

#4323 [#4169] feat(core): Supports the core logic of the ownership
  api/src/main/java/org/apache/gravitino/MetadataObject.java
  api/src/main/java/org/apache/gravitino/MetadataObjects.java
  api/src/main/java/org/apache/gravitino/authorization/Owner.java
  api/src/main/java/org/apache/gravitino/authorization/Privilege.java
  api/src/main/java/org/apache/gravitino/authorization/Privileges.java
  api/src/main/java/org/apache/gravitino/authorization/SecurableObject.java
  core/src/main/java/org/apache/gravitino/EntityStore.java
  core/src/main/java/org/apache/gravitino/GravitinoEnv.java
  core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/org/apache/gravitino/authorization/OwnerManager.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/OwnerMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/po/OwnerRelPO.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/CatalogMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/FilesetMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/MetalakeMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/TableMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/TopicMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java
  core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
  core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestOwnerMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/utils/TestPOConverters.java
  core/src/test/resources/h2/schema-h2.sql
  scripts/h2/schema-0.6.0-h2.sql
  scripts/mysql/schema-0.6.0-mysql.sql
  scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
Labels: branch-0.6

#4358 [#3817] fix(catalog-postgresql): Fix bugs when creating a schema or table using upper-case name.
  catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
  catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Labels: need backport, branch-0.6

#4355 [#4351] [improvement] UI: Switch catalog properties from immutable to mutable
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
Labels: branch-0.6

#4347 [#4228] improvement(client-python): Add Schema Error Handler and related exceptions, test cases in client-python
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/exceptions/base.py
  clients/client-python/gravitino/exceptions/handlers/schema_error_handler.py
  clients/client-python/tests/integration/test_schema.py
  clients/client-python/tests/unittests/test_error_handler.py
Labels: branch-0.6

#4292 [#4291] feat(catalog-lakehouse-paimon): Support Paimon table with primary keys in Gravitino
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/GravitinoPaimonTable.java
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogOperations.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/TestGravitinoPaimonTable.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
Labels: branch-0.6

#4354 [#4295] feat(server): Add REST API for the owner
  common/src/main/java/org/apache/gravitino/dto/authorization/OwnerDTO.java
  common/src/main/java/org/apache/gravitino/dto/requests/OwnerSetRequest.java
  common/src/main/java/org/apache/gravitino/dto/responses/OwnerResponse.java
  common/src/main/java/org/apache/gravitino/dto/responses/SetResponse.java
  common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
  core/src/main/java/org/apache/gravitino/GravitinoEnv.java
  server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java
  server/src/main/java/org/apache/gravitino/server/web/rest/OperationType.java
  server/src/main/java/org/apache/gravitino/server/web/rest/OwnerOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestOwnerOperations.java
Labels: branch-0.6

#4375 [#4115] feat(api): add validate check for decimal(0,0)
  api/src/main/java/org/apache/gravitino/rel/types/Types.java
  api/src/test/java/org/apache/gravitino/rel/TestTypes.java
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.6

#4390 [#4389] fix(iceberg-rest-server): add conf directory to classpath if starting standalone Iceberg REST catalog server in Gravitino package
  bin/common.sh
  bin/gravitino-iceberg-rest-server.sh
Labels: branch-0.6

#4387 [#2110] fix(ui): refine network error msg
  web/src/components/StyledToast.js
  web/src/lib/utils/axios/index.js
Labels: branch-0.6

#4343 [#3173] fix(doris-catalog): Fix the bug when create doris table with empty property
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/DorisCatalog.java
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/DorisTablePropertiesMetadata.java
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/TestDorisCatalog.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTablePartitionOperations.java
  docs/gravitino-server-config.md
  docs/jdbc-doris-catalog.md
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageDorisTest.java
Labels: need backport, branch-0.6

#4388 [#4180] fix(ui): show the required key msg when submit validate
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
Labels: branch-0.6

#4399 [#4153] fix(ui): Reset table props when reset tables data
  web/src/lib/store/metalakes/index.js
Labels: branch-0.6

#4348 Fix potential NullPointerException in UserContext by adding null check for parentContext.
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/UserContext.java
Labels: branch-0.6

#4349 [#3916] feat(catalog-lakehouse-paimon): Support alter table for Paimon Catalog
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogOperations.java
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonTablePropertiesMetadata.java
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/ops/PaimonCatalogOps.java
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TableOpsUtils.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/TestGravitinoPaimonTable.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/ops/TestPaimonCatalogOps.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestTableOpsUtils.java
Labels: branch-0.6

#4419 [#3929] fix(trino-connector): Fix the jdbc-postgresql/00004_query_pushdown.sql under catalog pg failed
  integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00004_query_pushdown.txt
Labels: branch-0.6

#4440 [#4439] fix: add **/*.out in list of exclusions
  build.gradle.kts
Labels: branch-0.6

#4444 [#4442] feat(client-python): Publish Python client to Apache Gravitino official account
  clients/client-python/.gitignore
  clients/client-python/build.gradle.kts
  clients/client-python/setup.py
  docs/how-to-use-python-client.md
Labels: branch-0.6

#4435 [#4433] Improvement(catalog-lakehouse-paimon): Update Paimon Catalog doc
  docs/lakehouse-paimon-catalog.md
Labels: branch-0.6

#4431 [MINOR] support publish Gravitino Iceberg REST catalog server docker image
  .github/workflows/docker-image.yml
  dev/docker/iceberg-rest-server/Dockerfile
Labels: branch-0.6

#4345 [#4227] improvement(client-python): Add Catalog Error Handler and related exceptions, test cases in client-python
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/constants/error.py
  clients/client-python/gravitino/dto/dto_converters.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/responses/catalog_response.py
  clients/client-python/gravitino/exceptions/base.py
  clients/client-python/gravitino/exceptions/handlers/catalog_error_handler.py
  clients/client-python/tests/integration/test_catalog.py
  clients/client-python/tests/unittests/test_error_handler.py
Labels: branch-0.6

#4458 [#4457] improvement(client-python): According Apache #pypi specification
  clients/client-python/setup.py
  docs/how-to-use-gvfs.md
  docs/how-to-use-python-client.md
Labels: branch-0.6

#4464 [HOTFIX] fix(build): Fix RAT issue in local build
  build.gradle.kts
Labels: branch-0.6

#4436 [#4424] Improvement (trino-connector): Upgrade the Hive image version for the Trino tester.
  .github/workflows/backend-integration-test.yml
  .github/workflows/cron-integration-test.yml
  integration-test/trino-it/docker-compose.yaml
  integration-test/trino-it/init/hive/init.sh
  integration-test/trino-it/launch.sh
  integration-test/trino-it/shutdown.sh
Labels: upload log, branch-0.6

#4468 [#4472 ] fix(CI pipeline): Fixed Doris test failure as a result of excessive disk usage
  dev/ci/util_free_space.sh
Labels: upload log, branch-0.6

#4479 [#4478] feat(conf): unify the configuration file permission to 755
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-jdbc-doris/build.gradle.kts
  catalogs/catalog-jdbc-mysql/build.gradle.kts
  catalogs/catalog-jdbc-postgresql/build.gradle.kts
  catalogs/catalog-kafka/build.gradle.kts
  catalogs/catalog-lakehouse-iceberg/build.gradle.kts
  catalogs/catalog-lakehouse-paimon/build.gradle.kts
  iceberg/iceberg-rest-server/build.gradle.kts
Labels: branch-0.6

#4462 [#4441] feat(script): improve message when start server failed
  bin/gravitino-iceberg-rest-server.sh
  bin/gravitino.sh
Labels: branch-0.6

#4403 [#4386] Fix(spark-connector): spark connector build failed with scala2.13
  .github/workflows/build.yml
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/extensions/IcebergExtendedDataSourceV2Strategy.java
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/utils/ConnectorUtil.java
  spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/sql/SQLQueryTestHelper.java
Labels: branch-0.6

#4465 [#4463] fix(tests): remove the wrong tag on test class
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTablePartitionOperations.java
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/CloseContainerExtension.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/ranger/AbstractRangerIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/ranger/RangerHiveIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/client/AuditIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/client/MetalakeIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/KerberosOperationsIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/OAuth2OperationsIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/VersionOperationsIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
Labels: branch-0.6

#4426 [#4408] Calls to code marked @VisibleForTesting in production code
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/kerberos/KerberosClient.java
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/CatalogUtils.java
Labels: branch-0.6

#4448 [#1903] feat(clients): add equals for `GravitinoMetalake`.
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoMetalake.java
Labels: branch-0.6

#4499 [#4500] fix(docs) Fix doc typo issue
  docs/flink-connector/flink-catalog-hive.md
  docs/how-to-build.md
  docs/lakehouse-paimon-catalog.md
  docs/trino-connector/trino-connector.md
Labels: branch-0.6

#4504 [#4503] fix(doc): Revise the compatibility description of the Hive catalog
  docs/apache-hive-catalog.md
Labels: branch-0.6

#4420 [3844]fix(catalog-mysql) Add the version checking for the MYSQL JDBC driver
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/MySQLProtocolCompatibleCatalogOperations.java
  catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysql.java
  catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlCatalogOperations.java
Labels: branch-0.6

#4512 [MINOR] docs: polish 0.6 document
  docs/flink-connector/flink-connector.md
  docs/iceberg-rest-service.md
  docs/lakehouse-paimon-catalog.md
  docs/spark-connector/spark-catalog-iceberg.md
Labels: branch-0.6

#4501 [#3232] fix(client): Fix the deleting role issues with irregular name
  clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  common/src/main/java/org/apache/gravitino/dto/authorization/SecurableObjectDTO.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/OwnerIT.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Labels: branch-0.6

#4395 [#4393] improvement(docs): Refine authentication information about Iceberg rest catalog and Add IT for Kerberos Hive backend.
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergTableOps.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergTableOpsManager.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTHiveCatalogIT.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRestKerberosHiveCatalogIT.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/util/IcebergRESTServerManagerForDeploy.java
Labels: branch-0.6

#4526 [Minor] improvement(docs): Change version from 0.6.0 to 0.6.0-incubating
  dev/release/update-java-doc-version.sh
  docs/index.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.6

#4489 [#4321] improvement(docs): Update docs for multiple authentication
  docs/security.md
  docs/webui.md
  server-common/src/main/java/org/apache/gravitino/server/authentication/AuthenticationFilter.java
Labels: branch-0.6

#4527 [Minor] improvement(docs): Polish docs
  docs/how-to-use-relational-backend-storage.md
  docs/manage-relational-metadata-using-gravitino.md
  docs/manage-tags-in-gravitino.md
Labels: branch-0.6

#4519 [#2242] docs(open-api): Add the open-api for access control
  docs/open-api/groups.yaml
  docs/open-api/openapi.yaml
  docs/open-api/owners.yaml
  docs/open-api/permissions.yaml
  docs/open-api/roles.yaml
  docs/open-api/users.yaml
Labels: branch-0.6

#4544 [Minor] improve(doc) : Update Paimon Catalog doc in `manage-relational-metadata-using-gravitino.md`
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.6

#4543 [#4542] fix(catalog-postgresql): Fix the problem that Gravitino is unable to drop upper-case PG schema.
  catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Labels: branch-0.6

#4541 [#4540] fix(core): Support alter tag with null comment
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/TagIT.java
Labels: branch-0.6

#4552 [MINOR] fix(openAPI): fix wrong indent in `owners.yaml`
  docs/open-api/owners.yaml
Labels: branch-0.6

#4555 [MINOR] fix(docs): Fix the link and slug
  docs/security/how-to-authenticate.md
  docs/security/how-to-use-cors.md
  docs/security/how-to-use-https.md
Labels: branch-0.6

#4562 [Minor] improve(doc): Update docs about partition management for Doris catalog
  docs/jdbc-doris-catalog.md
  docs/manage-table-partition-using-gravitino.md
Labels: branch-0.6

#4565 [Minor] improvement(docs): Fix and polish docs.
  docs/security/how-to-authenticate.md
  docs/security/how-to-use-https.md
  docs/security/security.md
Labels: branch-0.6

#4497 [#3650] fix (trino-connector): Fix failed to run the tester jdbc-mysql/00008_alter_catalog in Trino distribution environment
  integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00008_alter_catalog.txt
  integration-test/trino-it/docker-compose.yaml
  integration-test/trino-it/init/hive/init.sh
  trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/table/GravitinoSystemTableCatalog.java
  trino-connector/src/test/java/org/apache/gravitino/trino/connector/GravitinoMockServer.java
Labels: branch-0.6

#4560 [#4559] Improvement (docs): Rename the Gravitino connector to Gravitino Trino connector in docs
  docs/assets/trino/create-gravitino-trino-connector.jpg
  docs/trino-connector/catalog-hive.md
  docs/trino-connector/catalog-iceberg.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
  docs/trino-connector/configuration.md
  docs/trino-connector/development.md
  docs/trino-connector/index.md
  docs/trino-connector/installation.md
  docs/trino-connector/requirements.md
  docs/trino-connector/sql-support.md
  docs/trino-connector/supported-catalog.md
  docs/trino-connector/trino-connector.md
Labels: branch-0.6

#4346 [#3818][#4100] Improvement(client-python): Replace all assert in client-python & fix: Validate methods of request in client-python are not correct
  clients/client-python/gravitino/auth/default_oauth2_token_provider.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/client/gravitino_version.py
  clients/client-python/gravitino/dto/requests/catalog_create_request.py
  clients/client-python/gravitino/dto/requests/schema_create_request.py
  clients/client-python/gravitino/dto/responses/base_response.py
  clients/client-python/gravitino/dto/responses/catalog_response.py
  clients/client-python/gravitino/dto/responses/entity_list_response.py
  clients/client-python/gravitino/dto/responses/error_response.py
  clients/client-python/gravitino/dto/responses/fileset_response.py
  clients/client-python/gravitino/dto/responses/metalake_response.py
  clients/client-python/gravitino/dto/responses/oauth2_error_response.py
  clients/client-python/gravitino/dto/responses/oauth2_token_response.py
  clients/client-python/gravitino/dto/responses/schema_response.py
  clients/client-python/gravitino/dto/responses/version_response.py
  clients/client-python/gravitino/namespace.py
  clients/client-python/gravitino/rest/rest_utils.py
  clients/client-python/tests/integration/hdfs_container.py
  clients/client-python/tests/unittests/auth/test_oauth2_token_provider.py
  clients/client-python/tests/unittests/test_gravitino_version.py
Labels: branch-0.6

#4561 [#4506] fix(UI): Hide jdbc-password value in details page
  web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js
  web/src/components/DetailsDrawer.js
Labels: branch-0.6

#4577 [#4506] fix(UI): Hide jdbc-password value in details page
  web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js
  web/src/components/DetailsDrawer.js
Labels: branch-0.6

#4579 [MINOR] fix(doc): Add missing tag api in openAPI
  docs/open-api/catalogs.yaml
  docs/open-api/openapi.yaml
  docs/open-api/tags.yaml
Labels: branch-0.6

#4461 [#4460] feat(core): Add the method call of the authorizationPlugin
  core/src/main/java/org/apache/gravitino/GravitinoEnv.java
  core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java
  core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
  core/src/main/java/org/apache/gravitino/authorization/RoleManager.java
  core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java
  core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
Labels: branch-0.6

#4523 [#4072] improvement(docker-image): Transfer docker hub from datastrato to apache
  .github/workflows/cron-integration-test.yml
  .github/workflows/docker-image.yml
  CONTRIBUTING.md
  build.gradle.kts
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-jdbc-doris/build.gradle.kts
  catalogs/catalog-jdbc-mysql/build.gradle.kts
  catalogs/catalog-jdbc-postgresql/build.gradle.kts
  catalogs/catalog-kafka/build.gradle.kts
  catalogs/catalog-lakehouse-iceberg/build.gradle.kts
  catalogs/catalog-lakehouse-paimon/build.gradle.kts
  clients/client-python/build.gradle.kts
  dev/docker/build-docker.sh
  dev/docker/trino/Dockerfile
  docs/assets/publish-docker-image.jpg
  docs/assets/publish-docker-image.png
  docs/docker-image-details.md
  docs/getting-started.md
  docs/how-to-install.md
  docs/how-to-test.md
  docs/iceberg-rest-service.md
  docs/index.md
  docs/publish-docker-images.md
  flink-connector/build.gradle.kts
  iceberg/iceberg-rest-server/build.gradle.kts
  integration-test/build.gradle.kts
  integration-test/trino-it/docker-compose.yaml
  spark-connector/spark-common/build.gradle.kts
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.5/spark/build.gradle.kts
Labels: branch-0.6

#4594 [#3280] Improvement(ui): Truncate key and values detail properties
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java
  web/src/components/DetailsDrawer.js
Labels: branch-0.6

#4602 [Minor] Matomo test to see what (ASF approved) user stats we can obtain
  README.md
  docs/how-to-build.md
  docs/how-to-install.md
Labels: branch-0.6

#4518 [#4417] feat(build): Add release script to automate the release process
  LICENSE
  dev/release/do-release.sh
  dev/release/release-build.sh
  dev/release/release-tag.sh
  dev/release/release-util.sh
Labels: branch-0.6

#4612 [Minor] fix(CI): Fix CI pipeline configuration error.
  .github/workflows/backend-integration-test.yml
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java
Labels: branch-0.6

#3866 [#3807] feat(client-java): SimpleAuth can add a username when build a GravitinoClient
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
  clients/client-java/src/main/java/org/apache/gravitino/client/SimpleTokenProvider.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoClientBuilder.java
  docs/security/how-to-authenticate.md
Labels: branch-0.6

#4623 [#3963][followup] feat(core): Call the method ownerset of authorization plugin
  core/src/main/java/org/apache/gravitino/GravitinoEnv.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java
  core/src/main/java/org/apache/gravitino/authorization/OwnerManager.java
  core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
  core/src/main/java/org/apache/gravitino/authorization/RoleManager.java
  core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
  core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java
  core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java
  server/src/main/java/org/apache/gravitino/server/web/rest/OwnerOperations.java
Labels: branch-0.6

#4624 [#4587] docs: Refactor the security document and add authorization push-down page
  docs/apache-hive-catalog.md
  docs/assets/security/authorization-pushdown.png
  docs/assets/security/object.png
  docs/assets/security/privilege.png
  docs/assets/security/role.png
  docs/assets/security/user-group.png
  docs/assets/security/workflow.png
  docs/security/access-control.md
  docs/security/authorization-pushdown.md
Labels: branch-0.6

#4638 [#4637] improvement: Rename the table `securable_object_meta` field `entity_id` to `metadata_object_id`
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/po/SecurableObjectPO.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  scripts/h2/schema-0.6.0-h2.sql
  scripts/mysql/schema-0.6.0-mysql.sql
  scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
Labels: branch-0.6

#4642 [Minor] Remove URL parameter and add a coueple of more pages
  README.md
  docs/getting-started.md
  docs/how-to-build.md
  docs/how-to-install.md
  docs/how-to-upgrade.md
  docs/how-to-use-the-playground.md
  docs/index.md
Labels: branch-0.6

#4631 [#4630] feat(iceberg): remove S3 SDK jar from Gravitino Iceberg REST server
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  docs/spark-connector/spark-catalog-iceberg.md
  gradle/libs.versions.toml
  iceberg/iceberg-common/build.gradle.kts
Labels: branch-0.6

#4592 [#4586] fix(filesystem): Fix convert the actual path which storage location end with slash
  clients/client-python/gravitino/filesystem/gvfs.py
  clients/client-python/tests/unittests/test_gvfs_with_local.py
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
Labels: branch-0.6

#4647 [#4637] improvement(core): Rename the table `securable_object_meta` field `entity_id` to `metadata_object_id`
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/po/SecurableObjectPO.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  scripts/h2/schema-0.6.0-h2.sql
  scripts/mysql/schema-0.6.0-mysql.sql
  scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
Labels: cherry-pick

#4649 [#4646] docs(iceberg): fix Iceberg REST service doc
  docs/iceberg-rest-service.md
Labels: branch-0.6

#4653 [MINOR] fix(build): Add gradle.kts to iceberg parent module
  iceberg/build.gradle.kts
Labels: branch-0.6

#4667 [#4666] docs: correct reference from MySQL to PostgreSQL in JDBC cata…
  docs/jdbc-postgresql-catalog.md
Labels: branch-0.6

#4665 [#4664] fix(server): Add the missing annotations fo access control interfaces
  conf/gravitino.conf.template
  docs/security/access-control.md
  server-common/src/main/java/org/apache/gravitino/server/authorization/NameBindings.java
  server/src/main/java/org/apache/gravitino/server/web/rest/PermissionOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
Labels: branch-0.6

#4671 [Minor] improvement(CI): Fix backend tests fail occasionally as a result of CI pipeline timeout.
  .github/workflows/backend-integration-test.yml
Labels: branch-0.6

#4651 [#4662] improve(IT): Add ranger authorization Hive E2E test
  .github/workflows/access-control-integration-test.yml
  .github/workflows/backend-integration-test.yml
  LICENSE.bin
  NOTICE.bin
  authorizations/authorization-ranger/build.gradle.kts
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
  build.gradle.kts
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java
  catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogPropertiesMetadata.java
  core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
  core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
  core/src/test/java/org/apache/gravitino/connector/authorization/TestAuthorization.java
  gradle/libs.versions.toml
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/MySQLContainer.java
Labels: branch-0.6

#4677 [#4662] improve(IT): Add ranger authorization Hive E2E test
  .github/workflows/access-control-integration-test.yml
  .github/workflows/backend-integration-test.yml
  LICENSE.bin
  NOTICE.bin
  authorizations/authorization-ranger/build.gradle.kts
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
  build.gradle.kts
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java
  catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogPropertiesMetadata.java
  core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
  core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
  core/src/test/java/org/apache/gravitino/connector/authorization/TestAuthorization.java
  gradle/libs.versions.toml
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/MySQLContainer.java
Labels: upload log

#4686 [#4685] fix docs img inline style issue
  docs/getting-started.md
  docs/how-to-build.md
  docs/how-to-install.md
  docs/how-to-upgrade.md
  docs/how-to-use-the-playground.md
  docs/index.md
Labels: branch-0.6

#4689 [#4688] fix (docker): Fix the Trino playground Docker image cannot start up
  dev/docker/trino/Dockerfile
Labels: branch-0.6

#4692 [Minor] fix(docker-image): Fix bugs in publishing Iceberg rest server docker image
  .github/workflows/docker-image.yml
Labels: branch-0.6

#4670 [MINOR] Add originator of Gravitino to the NOTICE file
  NOTICE
  NOTICE.bin
  web/NOTICE
  web/NOTICE.bin
Labels: branch-0.6

#4702 [#4701] fix(docs): Fix the inconsistent privilege descriptions
  docs/security/access-control.md
Labels: branch-0.6

#4700 [#4695] Fix (python-client): Fix gradlew :clients:client-python:build failed if the package does not contain .git directory
  clients/client-python/gravitino/constants/root.py
  clients/client-python/scripts/generate_version.py
Labels: branch-0.6

#4704 [#4699] fix(server): The error response of addUser should meet the REST specification
  clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlNotAllowIT.java
  server/src/main/java/org/apache/gravitino/server/web/filter/AccessControlNotAllowedFilter.java
Labels: branch-0.6

#4715 [#4712] fix (trino-connector): Fix Iceberg JDBC backend tables can not found in Trino
  trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java
  trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergConnectorAdapter.java
  trino-connector/src/main/java/org/apache/gravitino/trino/connector/metadata/GravitinoCatalog.java
Labels: branch-0.6

#4729 [Minor] Update how-to-build.md
  docs/how-to-build.md
Labels: branch-0.6

#4741 [#4739] fix(docs): Correct the playground document errors
  docs/how-to-use-python-client.md
  docs/how-to-use-the-playground.md
Labels: branch-0.6

#4748 [#4745] fix(docs): Update the link address in DISCLAIMER_WIP.txt
  DISCLAIMER_WIP.txt
Labels: branch-0.6

#4750 [MINOR] fix(build): Fix some small bugs in the release script
  dev/release/release-build.sh
Labels: branch-0.6

#4752 [Minor] Minor English changes.
  docs/how-to-use-the-playground.md
Labels: branch-0.6

#4762 [Minor] Jupiter -> Jupyter
  docs/how-to-use-the-playground.md
Labels: branch-0.6

#4763 [#4760] Improvement (docs): Correct errors in the Trino connector document
  docs/trino-connector/catalog-hive.md
  docs/trino-connector/catalog-iceberg.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
  docs/trino-connector/development.md
Labels: branch-0.6

#4768 [#4767] fix(docs): Update the document of playground
  docs/how-to-use-the-playground.md
Labels: branch-0.6

#4784 [#4782] fix(doc): correct partiton doc
  docs/manage-table-partition-using-gravitino.md
Labels: branch-0.6

#4773 [Minor] improvement(docs): Fix docs problem about configuration default value
  docs/gravitino-server-config.md
  docs/security/how-to-use-cors.md
Labels: branch-0.6

#4781 [MINOR] Fix Spark and Flink download link
  docs/flink-connector/flink-connector.md
  docs/spark-connector/spark-connector.md
Labels: branch-0.6

#4771 [#4737] improvement(ui): update documentation link
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
  web/src/app/rootLayout/Footer.js
Labels: branch-0.6

#4776 [#4754] fix(docs): Optimize the document of access control
  docs/security/access-control.md
Labels: branch-0.6

#4794 [#4764] fix(docs): Fix several typos in docs
  docs/docker-image-details.md
  docs/how-to-build.md
  docs/how-to-use-python-client.md
Labels: branch-0.6

#4800 [#4785] improvement(docs): Remove the copy right `datastrato` in the picture.
  docs/assets/trino/show-catalogs.jpg
  docs/assets/webui/create-catalog.png
  docs/assets/webui/create-metalake-dialog.png
  docs/assets/webui/created-catalog.png
  docs/assets/webui/delete-metalake.png
  docs/assets/webui/demo-columns.png
  docs/assets/webui/demo-tables.png
  docs/assets/webui/fileset-details.png
  docs/assets/webui/login-with-oauth.png
  docs/assets/webui/metalake-catalogs-details.png
  docs/assets/webui/metalake-catalogs.png
  docs/assets/webui/metalake-details.png
  docs/assets/webui/metalake-list.png
  docs/assets/webui/metalakes-oauth.png
  docs/assets/webui/metalakes-simple.png
  docs/assets/webui/show-catalog-details.png
  docs/assets/webui/update-catalog.png
Labels: branch-0.6

#4802 [Minor] fix footer
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java
  web/src/app/rootLayout/Footer.js
Labels: branch-0.6

#4807 [#4805] format license headers for open api yaml files
  docs/open-api/catalogs.yaml
  docs/open-api/datatype.yaml
  docs/open-api/expression.yaml
  docs/open-api/filesets.yaml
  docs/open-api/groups.yaml
  docs/open-api/indexes.yaml
  docs/open-api/metalakes.yaml
  docs/open-api/openapi.yaml
  docs/open-api/owners.yaml
  docs/open-api/partitioning.yaml
  docs/open-api/partitions.yaml
  docs/open-api/permissions.yaml
  docs/open-api/roles.yaml
  docs/open-api/schemas.yaml
  docs/open-api/tables.yaml
  docs/open-api/tags.yaml
  docs/open-api/topics.yaml
  docs/open-api/users.yaml
Labels: branch-0.6

#4791 [#3514] improvement(flink-connector): add flink-connector-runtime to build flink connector
  .github/workflows/flink-integration-test.yml
  build.gradle.kts
  docs/flink-connector/flink-connector.md
  flink-connector/build.gradle.kts
  flink-connector/flink-runtime/build.gradle.kts
  flink-connector/flink/build.gradle.kts
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/DefaultPartitionConverter.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/PartitionConverter.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/PropertiesConverter.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalog.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/GravitinoCatalogManager.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalog.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalogFactory.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalogFactoryOptions.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/HivePropertiesConverter.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/store/GravitinoCatalogStore.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/store/GravitinoCatalogStoreFactory.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/store/GravitinoCatalogStoreFactoryOptions.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/FactoryUtils.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/PropertyUtils.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/TableUtils.java
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/TypeUtils.java
  flink-connector/flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/catalog/TestBaseCatalog.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/hive/TestHivePropertiesConverter.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkCommonIT.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkEnvIT.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/utils/TestUtils.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
  flink-connector/flink/src/test/resources/flink-tests/hive-site.xml
  flink-connector/flink/src/test/resources/log4j2.properties
  settings.gradle.kts
Labels: branch-0.6

#4813 [Minor] fix(docs): Fix docs mistake for partitioned table created by Trino
  docs/trino-connector/catalog-hive.md
Labels: branch-0.6

#4818 [#4812] fix(core): Make ensure the schema exists before creating tables and topics
  core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java
  core/src/main/java/org/apache/gravitino/catalog/TopicOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestPartitionNormalizeDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestPartitionOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTopicOperationDispatcher.java
  server/src/main/java/org/apache/gravitino/server/web/rest/TableOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/TopicOperations.java
Labels: branch-0.6

#4822 [MINOR] fix(CI): exclude flinkIT from backendIT
  .github/workflows/backend-integration-test.yml
Labels: branch-0.6

#4821 [#4803] improvement(client-python): Delete egg-info directory due to Python package renamed improvement
  clients/client-python/build.gradle.kts
Labels: branch-0.6

#4826 [#4812] fix(core): Make ensure the schema exists before creating tables and topics
  core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java
  core/src/main/java/org/apache/gravitino/catalog/TopicOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestPartitionNormalizeDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestPartitionOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTopicOperationDispatcher.java
  server/src/main/java/org/apache/gravitino/server/web/rest/TableOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/TopicOperations.java
Labels: cherry-pick
