Repository apache/gravitino, pull requests merged in 2024-01, with the labels that each got.

#1260 [MINOR] improve(doc): Improve the index to reorganize the order of the docs
  docs/how-to-install.md
  docs/iceberg-rest-service.md
  docs/index.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
Labels: need backport, branch-0.3

#1283 Happy new year!
  NOTICE
  NOTICE.bin
Labels: need backport, branch-0.3

#1203 [#1135] improvement(docs): Add docs about tables advanced feature like partitioning
  docs/manage-metadata-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order.md
Labels: need backport, branch-0.3

#1301 [#1299] Fix the copyright year
  web/lib/layout/Footer.js
Labels: need backport, branch-0.3

#1300 [MINOR] doc: Improve English and add warning that web UI only works in Chrome
  docs/docker-image-details.md
  web/README.md
Labels: need backport, branch-0.3

#1312 [#1311] bugfix(docker): Unable to run datastrato/trino Docker in AWS
  dev/docker/trino/conf/node.properties
Labels: need backport, branch-0.3

#1302 Fix minor grammar errors and English mistakes in documentation.
  README.md
  docs/apache-hive-catalog.md
  docs/docker-image-details.md
  docs/getting-started.md
  docs/gravitino-server-config.md
  docs/how-to-build.md
  docs/how-to-install.md
  docs/how-to-sign-releases.md
  docs/how-to-test.md
  docs/how-to-use-the-playground.md
  docs/iceberg-rest-service.md
  docs/index.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/metrics.md
  docs/overview.md
  docs/publish-docker-images.md
  docs/security.md
  docs/table-partitioning-bucketing-sort-order.md
  docs/webui.md
Labels: need backport, branch-0.3

#1322 [MINOR] fix typo in URL
  CONTRIBUTING.md
Labels: need backport, branch-0.3

#1321 [#1151] fix(UI): Fix status cache after modified a Metalake
  web/app/(home)/MetalakeList.js
  web/app/(home)/TableHeader.js
Labels: need backport, branch-0.3

#1323 [MINOR] Add note on supported build systems
  README.md
Labels: need backport, branch-0.3

#1308 [#1113][#1224] improvement(UI): TS support and improve global request handing
  build.gradle.kts
  web/.prettierignore
  web/.vscode/settings.json
  web/LICENSE.bin
  web/app/layout.js
  web/jsconfig.json
  web/lib/api/auth/index.js
  web/lib/api/catalogs/index.js
  web/lib/api/index.js
  web/lib/api/metalakes/index.js
  web/lib/api/schemas/index.js
  web/lib/api/tables/index.js
  web/lib/api/version/index.js
  web/lib/enums/httpEnum.ts
  web/lib/provider/session.js
  web/lib/store/auth/index.js
  web/lib/store/metalakes/index.js
  web/lib/store/sys/index.js
  web/lib/utils/axios/Axios.ts
  web/lib/utils/axios/axiosCancel.ts
  web/lib/utils/axios/axiosRetry.ts
  web/lib/utils/axios/axiosTransform.ts
  web/lib/utils/axios/checkStatus.ts
  web/lib/utils/axios/helper.ts
  web/lib/utils/axios/index.ts
  web/lib/utils/index.js
  web/lib/utils/is.ts
  web/licenses/lodash.txt
  web/licenses/qs.txt
  web/licenses/side-channel.txt
  web/licenses/sweetalert2.txt
  web/licenses/undici-types.txt
  web/licenses/vben.txt
  web/package.json
  web/tsconfig.json
  web/types/axios.d.ts
  web/types/global.d.ts
  web/yarn.lock
Labels: need backport, branch-0.3

#1239 [#1237] fix(trino): Fix dropping iceberg schema failure
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogConnectorMetadata.java
Labels: need backport, branch-0.3

#1330 [#1150] fix(UI): Fix details comment error and improve components check
  web/app/metalakes/DetailsView.js
  web/app/metalakes/MetalakeView.js
  web/lib/layout/Layout.js
  web/lib/provider/client.js
  web/lib/provider/index.js
Labels: need backport, branch-0.3

#1337 [#1282] bugfix(CI) Automatically trigger CI for auto-cherry-pick workflow
  .github/workflows/auto-cherry-pick.yml
Labels: need backport, branch-0.3

#1305 [#1295] improvement(CI): separate trino image for CI and users
  dev/docker/build-docker.sh
  dev/docker/trino/Dockerfile
  docs/docker-image-details.md
Labels: need backport, branch-0.3

#1342 [#1282] bugfix(CI) Automatically trigger CI for auto-cherry-pick workflow
  .github/workflows/auto-cherry-pick.yml
Labels: need backport, cherry-pick

#1329 [#1328] fix(trino-connector): Fix the failed 'drop catalog' test on Trino image gravitino-ci-trino:0.1.3.
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Labels: need backport, branch-0.3

#1347 [#1328] fix(trino-connector): Fix the failed 'drop catalog' test on Trino image gravitino-ci-trino:0.1.3.
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Labels: need backport, cherry-pick

#1344 [#1295] improvement(CI): separate trino image for CI and users
  dev/docker/build-docker.sh
  dev/docker/trino/Dockerfile
  docs/docker-image-details.md
Labels: need backport, cherry-pick

#1353 [#1267] fix: Add missing headers and license
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/service/MysqlService.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/service/PostgreSqlService.java
Labels: need backport, branch-0.3

#1360 [#1267] fix: Add missing headers and license
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/service/MysqlService.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/service/PostgreSqlService.java
Labels: need backport, cherry-pick

#1376 [#1317] fix(trino-connector): Support Fixed type conversion
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
Labels: need backport, cherry-pick

#1365 [#1001] fix(UI): Fix null requests in the web UI
  web/app/metalakes/MetalakeView.js
  web/lib/store/metalakes/index.js
Labels: need backport, branch-0.3

#1378 [#1001] fix(UI): Fix null requests in the web UI
  web/app/metalakes/MetalakeView.js
  web/lib/store/metalakes/index.js
Labels: need backport, cherry-pick

#1351 [#1273] fix(UI): Fix cache values in the dialog when create a catalog
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, branch-0.3

#1375 [#1350] fix(UI): Fix fields validation when create a catalog in the web UI
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, branch-0.3

#1387 [#1350] fix(UI): Fix fields validation when create a catalog in the web UI
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, cherry-pick

#1382 [#1273] fix(UI): Fix cache values in the dialog when create a catalog
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, cherry-pick

#1394 [#1391] fix(UI): Fix update metalake error in the web UI
  web/app/(home)/CreateMetalakeDialog.js
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, branch-0.3

#1400 [#1391] fix(UI): Fix update metalake error in the web UI
  web/app/(home)/CreateMetalakeDialog.js
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, cherry-pick

#1404 [#1403] fix(UI): Remove unnecessary fields when creating a catalog in the web UI
  web/app/metalakes/CreateCatalogDialog.js
  web/lib/provider/session.js
  web/lib/utils/axios/index.ts
Labels: need backport, branch-0.3

#1407 [#1403] fix(UI): Remove unnecessary fields when creating a catalog in the web UI
  web/app/metalakes/CreateCatalogDialog.js
  web/lib/provider/session.js
  web/lib/utils/axios/index.ts
Labels: need backport, cherry-pick

#1412 [#1428] improvement(UI): Filtering empty keys when create or update
  web/app/(home)/CreateMetalakeDialog.js
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, branch-0.3

#1430 [#1428] improvement(UI): Filtering empty keys when create or update
  web/app/(home)/CreateMetalakeDialog.js
  web/app/metalakes/CreateCatalogDialog.js
Labels: need backport, cherry-pick

#1426 [#1422] fix(doc): Update the CONTRIBUTING.MD to fix the link error
  CONTRIBUTING.md
Labels: need backport, branch-0.3

#1438 [#1422] fix(doc): Update the CONTRIBUTING.MD to fix the link error
  CONTRIBUTING.md
Labels: need backport, cherry-pick

#1464 [#1463] improvement(doc): Modify the change log for new Docker images
  docs/docker-image-details.md
Labels: need backport, branch-0.3

#1465 [#1463] improvement(doc): Modify the change log for new Docker images
  docs/docker-image-details.md
Labels: need backport, cherry-pick

#1466 [MINOR] docs: Fix some mistakes in docs
  docs/iceberg-rest-service.md
  docs/index.md
  docs/manage-metadata-using-gravitino.md
  docs/trino-connector/installation.md
Labels: need backport, branch-0.3

#1470 [MINOR] docs: Fix some mistakes in docs
  docs/iceberg-rest-service.md
  docs/index.md
  docs/manage-metadata-using-gravitino.md
  docs/trino-connector/installation.md
Labels: need backport, cherry-pick

#1516 [#1515] fix(jdbc): The format of jdbc-mysql.conf and jdbc-postgresql.conf is not correct.
  catalogs/catalog-jdbc-mysql/src/main/resources/jdbc-mysql.conf
  catalogs/catalog-jdbc-postgresql/src/main/resources/jdbc-postgresql.conf
Labels: bug, need backport, branch-0.3

#1593 [#1515] fix(jdbc): The format of jdbc-mysql.conf and jdbc-postgresql.conf is not correct.
  catalogs/catalog-jdbc-mysql/src/main/resources/jdbc-mysql.conf
  catalogs/catalog-jdbc-postgresql/src/main/resources/jdbc-postgresql.conf
Labels: bug, need backport, cherry-pick
