Repository apache/gravitino, pull requests merged in 2024-02, with the labels that each got.

#1852 [#1817] improvement(all): Remove warning informations when building with JDK17
  common/src/main/java/com/datastrato/gravitino/Config.java
  common/src/main/java/com/datastrato/gravitino/auth/AuthConstants.java
  common/src/main/java/com/datastrato/gravitino/auth/AuthenticatorType.java
  common/src/main/java/com/datastrato/gravitino/config/ConfigBuilder.java
  common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  common/src/main/java/com/datastrato/gravitino/dto/AuditDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/CatalogDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/DistributionDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/BucketPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/DayPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/Partitioning.java
  common/src/main/java/com/datastrato/gravitino/dto/requests/AddPartitionsRequest.java
  common/src/main/java/com/datastrato/gravitino/dto/requests/CatalogUpdateRequest.java
Labels: need backport, branch-0.4

#1858 [#1651][#1274] docs: Add example for complex data type of column
  docs/manage-metadata-using-gravitino.md
  docs/open-api/datatype.yaml
Labels: need backport, branch-0.4

#1864 [#1651][#1274] docs: Add example for complex data type of column
  docs/manage-metadata-using-gravitino.md
  docs/open-api/datatype.yaml
Labels: need backport, cherry-pick

#1863 [#1817] improvement(all): Remove warning informations when building with JDK17
  common/src/main/java/com/datastrato/gravitino/Config.java
  common/src/main/java/com/datastrato/gravitino/auth/AuthConstants.java
  common/src/main/java/com/datastrato/gravitino/auth/AuthenticatorType.java
  common/src/main/java/com/datastrato/gravitino/config/ConfigBuilder.java
  common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  common/src/main/java/com/datastrato/gravitino/dto/AuditDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/CatalogDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/DistributionDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/BucketPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/DayPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/Partitioning.java
  common/src/main/java/com/datastrato/gravitino/dto/requests/AddPartitionsRequest.java
  common/src/main/java/com/datastrato/gravitino/dto/requests/CatalogUpdateRequest.java
Labels: need backport, cherry-pick

#1871 [#1868] improvement: Rename the variable to avoid misunderstanding
  core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java
Labels: cherry-pick, branch-0.4

#1899 [#1893] improvement(build): treat warnings as errors in lint OpenAPI
  docs/build.gradle.kts
Labels: branch-0.4

#1896 [#1868] improvement: Rename the variable to avoid misunderstanding
  core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java
Labels: cherry-pick

#1905 [#1893] improvement(build): treat warnings as errors in lint OpenAPI
  docs/build.gradle.kts
Labels: cherry-pick

#1851 [#1847] Improvement(mysql): Add unit testing for jdbc catalog and organize code.
  catalogs/catalog-jdbc-mysql/build.gradle.kts
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
  catalogs/catalog-jdbc-postgresql/build.gradle.kts
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/MysqlTableOperationsIT.java
Labels: branch-0.4

#1862 [#1861] improvement(core): Fix unstable tests about tree lock
  core/src/test/java/com/datastrato/gravitino/lock/TestLockManager.java
Labels: cherry-pick, branch-0.4

#1970 [#1861] improvement(core): Fix unstable tests about tree lock
  core/src/test/java/com/datastrato/gravitino/lock/TestLockManager.java
Labels: cherry-pick

#1860 [#1710] improve(web): improve tree view performance
  web/LICENSE.bin
  web/app/ui/MetalakeList.js
  web/app/ui/metalakes/LeftContent.js
  web/app/ui/metalakes/MetalakeTree.js
  web/app/ui/metalakes/MetalakeView.js
  web/app/ui/metalakes/TableView.js
  web/app/ui/metalakes/page.js
  web/lib/api/metalakes/index.js
  web/lib/layout/navigation-events.js
  web/lib/store/metalakes/index.js
  web/lib/utils/index.js
  web/licenses/antd.txt
  web/package.json
  web/pnpm-lock.yaml
Labels: need backport, branch-0.4

#1977 [#1710] improve(web): improve tree view performance
  web/LICENSE.bin
  web/app/ui/MetalakeList.js
  web/app/ui/metalakes/LeftContent.js
  web/app/ui/metalakes/MetalakeTree.js
  web/app/ui/metalakes/MetalakeView.js
  web/app/ui/metalakes/TableView.js
  web/app/ui/metalakes/page.js
  web/lib/api/metalakes/index.js
  web/lib/layout/navigation-events.js
  web/lib/store/metalakes/index.js
  web/lib/utils/index.js
  web/licenses/antd.txt
  web/package.json
  web/pnpm-lock.yaml
Labels: need backport, cherry-pick

#1965 [#1847] Improvement(mysql): Add unit testing for jdbc catalog and organize code.
  catalogs/catalog-jdbc-mysql/build.gradle.kts
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
  catalogs/catalog-jdbc-postgresql/build.gradle.kts
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/MysqlTableOperationsIT.java
Labels: cherry-pick

#1990 [#1798] Improvement(doc): Upgrade doc for index, auto_increment, mysql_properties
  docs/apache-hive-catalog.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/open-api/indexes.yaml
  docs/open-api/tables.yaml
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: need backport, cherry-pick

#1995 [#1944] fix(core): Make constructor of MetricsSource.java protected
  core/src/main/java/com/datastrato/gravitino/metrics/source/MetricsSource.java
Labels: need backport, branch-0.4

#1996 [#1944] fix(core): Make constructor of MetricsSource.java protected
  core/src/main/java/com/datastrato/gravitino/metrics/source/MetricsSource.java
Labels: need backport, cherry-pick

#1998 [#1984] improvement(docs): Upgrade the link of java docs from 0.3.1 to 0.4.0
  docs/getting-started.md
  docs/index.md
  docs/manage-metadata-using-gravitino.md
Labels: cherry-pick, branch-0.4

#1999 [#1984] improvement(docs): Upgrade the link of java docs from 0.3.1 to 0.4.0
  docs/getting-started.md
  docs/index.md
  docs/manage-metadata-using-gravitino.md
Labels: cherry-pick

#1975 [#1974] fix(hive): Hive table listPartitions reduces HMS RPC calls
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTableOperations.java
Labels: need backport, branch-0.4

#2000 [#1974] fix(hive): Hive table listPartitions reduces HMS RPC calls
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTableOperations.java
Labels: need backport, cherry-pick

#1991 [#1134] docs: Add user doc of expression
  docs/expression.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: branch-0.4

#2004 [#1134] docs: Add user doc of expression
  docs/expression.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: cherry-pick

#2007 [#1983] improve(web): Improve TreeView component interaction
  web/app/ui/metalakes/DetailsView.js
  web/app/ui/metalakes/MetalakeTree.js
  web/app/ui/metalakes/MetalakeView.js
  web/app/ui/metalakes/RightContent.js
  web/app/ui/metalakes/TableView.js
  web/app/ui/metalakes/TabsContent.js
  web/lib/store/metalakes/index.js
  web/lib/utils/index.js
Labels: need backport, branch-0.4

#2005 [#1986] improvement(docs): Fix some code issues in doc
  docs/manage-metadata-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: need backport, branch-0.4

#2008 [MINOR] improve(web): improve format of the error message
  web/lib/utils/axios/checkStatus.ts
Labels: need backport, branch-0.4

#2010 [#1986] improvement(docs): Fix some code issues in doc
  docs/manage-metadata-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: need backport, cherry-pick

#2009 [#1983] improve(web): Improve TreeView component interaction
  web/app/ui/metalakes/DetailsView.js
  web/app/ui/metalakes/MetalakeTree.js
  web/app/ui/metalakes/MetalakeView.js
  web/app/ui/metalakes/RightContent.js
  web/app/ui/metalakes/TableView.js
  web/app/ui/metalakes/TabsContent.js
  web/lib/store/metalakes/index.js
  web/lib/utils/index.js
Labels: need backport, cherry-pick

#2011 [MINOR] improve(web): improve format of the error message
  web/lib/utils/axios/checkStatus.ts
Labels: need backport, cherry-pick

#2013 [MINOR] improve(web): improve table cell format
  web/app/ui/metalakes/TableView.js
Labels: need backport, branch-0.4

#2014 [#1987] improvement(build): Take warning information as error when build java docs
  build.gradle.kts
Labels: need backport, branch-0.4

#2012 [MINOR] docs(jdbc): polish jdbc document
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
Labels: need backport, branch-0.4

#2015 [MINOR] improve(web): improve table cell format
  web/app/ui/metalakes/TableView.js
Labels: need backport, cherry-pick

#2016 [#1987] improvement(build): Take warning information as error when build java docs
  build.gradle.kts
Labels: need backport, cherry-pick

#2017 [MINOR] docs(jdbc): polish jdbc document
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
Labels: need backport, cherry-pick

#2019 [#2018] docs: Add OAS of partition management
  docs/open-api/openapi.yaml
  docs/open-api/partitions.yaml
Labels: branch-0.4

#2020 [#2018] docs: Add OAS of partition management
  docs/open-api/openapi.yaml
  docs/open-api/partitions.yaml
Labels: cherry-pick

#2022 [#1856] improvement(doc): Add Docker image 0.4.0 change log
  docs/docker-image-details.md
Labels: need backport, branch-0.4

#2024 [#1856] improvement(doc): Add Docker image 0.4.0 change log
  docs/docker-image-details.md
Labels: need backport, cherry-pick

#1982 [#1979] fix(test): add timeout and retry when downloading chrome
  integration-test/src/main/java/com/datastrato/gravitino/integration/test/util/ITUtils.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java
Labels: need backport, branch-0.4

#2026 [#1979] fix(test): add timeout and retry when downloading chrome
  integration-test/src/main/java/com/datastrato/gravitino/integration/test/util/ITUtils.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java
Labels: need backport, cherry-pick

#2030 [#2027] fix(trino-connector): Fix the bug that `format` configuration can't overwrite default `InputFormat` value.
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HivePropertyMeta.java
Labels: need backport, branch-0.4

#1248 [MINOR] docs(lakehouse-iceberg): polish Iceberg REST service document
  docs/iceberg-rest-service.md
Labels: minor, need backport, branch-0.4

#2028 [MINOR] improve(docs): update the web usage document to 0.4.0
  docs/assets/webui/delete-catalog.png
  docs/assets/webui/show-catalog-details.png
  docs/assets/webui/tree-view-reload-catalog.png
  docs/assets/webui/tree-view.png
  docs/assets/webui/update-catalog.png
  docs/webui.md
  web/app/ui/metalakes/CreateCatalogDialog.js
Labels: need backport, branch-0.4

#2032 [MINOR] docs(lakehouse-iceberg): polish Iceberg REST service document
  docs/iceberg-rest-service.md
Labels: minor, need backport, cherry-pick

#2031 [#2027] fix(trino-connector): Fix the bug that `format` configuration can't overwrite default `InputFormat` value.
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HivePropertyMeta.java
Labels: need backport, cherry-pick

#2021 [#1857] improvement: Add an Iceberg REST service demo
  docs/how-to-use-the-playground.md
  docs/iceberg-rest-service.md
Labels: need backport, branch-0.4

#2038 [#1857] improvement: Add an Iceberg REST service demo
  docs/how-to-use-the-playground.md
  docs/iceberg-rest-service.md
Labels: need backport, cherry-pick

#2033 [MINOR] improve(docs): update the web usage document to 0.4.0
  docs/assets/webui/delete-catalog.png
  docs/assets/webui/show-catalog-details.png
  docs/assets/webui/tree-view-reload-catalog.png
  docs/assets/webui/tree-view.png
  docs/assets/webui/update-catalog.png
  docs/webui.md
  web/app/ui/metalakes/CreateCatalogDialog.js
Labels: need backport, cherry-pick

#2043 [#2042] improvement(doc): Unify the style of configuration options
  docs/security.md
Labels: need backport, branch-0.4

#2003 [#1590] docs: Add doc for column default value
  docs/apache-hive-catalog.md
  docs/expression.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/open-api/tables.yaml
Labels: need backport, branch-0.4

#2040 [MINOR] docs(lakehouse-iceberg): polish iceberg document
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
Labels: need backport, branch-0.4

#2029 [#1859] docs: Add user doc for partition management
  docs/manage-table-partition-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: need backport, branch-0.4

#2047 [MINOR] docs: Adjust the position of the example to fit the Docusaurus OpenAPI plugin
  docs/open-api/partitions.yaml
Labels: need backport, branch-0.4

#2051 [MINOR] docs: Adjust the position of the example to fit the Docusaurus OpenAPI plugin
  docs/open-api/partitions.yaml
Labels: need backport, cherry-pick

#2049 [#1859] docs: Add user doc for partition management
  docs/manage-table-partition-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
Labels: need backport, cherry-pick

#2045 [#2042] improvement(doc): Unify the style of configuration options
  docs/security.md
Labels: need backport, cherry-pick

#2048 [MINOR] docs(lakehouse-iceberg): polish iceberg document
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
Labels: need backport, cherry-pick

#2053 [#2052] fix(IT): improve the timeout handle of web driver
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverManager.java
Labels: need backport, branch-0.4

#2057 [#2052] fix(IT): improve the timeout handle of web driver
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverManager.java
Labels: need backport, cherry-pick

#2046 [#1590] docs: Add doc for column default value
  docs/apache-hive-catalog.md
  docs/expression.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/manage-metadata-using-gravitino.md
  docs/open-api/tables.yaml
Labels: need backport, cherry-pick

#2063 [#1754] fix(web): fix oauth CORS error
  web/lib/api/auth/index.js
  web/lib/provider/session.js
  web/lib/store/auth/index.js
Labels: need backport, cherry-pick

#2044 [#2037] fix(mysql-catalog): Fix MySQL/PG wild card and case sensitive issues in table name
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Labels: need backport, branch-0.4

#2064 [#1274] docs: Add complex data type example to `HiveTableCreate`
  docs/open-api/tables.yaml
Labels: need backport, branch-0.4

#2066 [#1274] docs: Add complex data type example to `HiveTableCreate`
  docs/open-api/tables.yaml
Labels: need backport, cherry-pick

#2070 [MINOR] docs: Condense the summary to fit the Docusaurus open api plugin
  docs/open-api/catalogs.yaml
  docs/open-api/metalakes.yaml
  docs/open-api/partitions.yaml
  docs/open-api/schemas.yaml
  docs/open-api/tables.yaml
Labels: need backport, branch-0.4

#2071 [MINOR] docs: Condense the summary to fit the Docusaurus open api plugin
  docs/open-api/catalogs.yaml
  docs/open-api/metalakes.yaml
  docs/open-api/partitions.yaml
  docs/open-api/schemas.yaml
  docs/open-api/tables.yaml
Labels: need backport, cherry-pick

#2069 [#2067] Fix the bugs that list tables in schema `pg_` will get all tables in schema starts with `pg`
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Labels: need backport, branch-0.4

#2075 [#2067] Fix the bugs that list tables in schema `pg_` will get all tables in schema starts with `pg`
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Labels: need backport, cherry-pick

#1721 [#1313][#1471] feat(iceberg): Support struct column for iceberg
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ConvertUtil.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergType.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergTypeVisitor.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestConvertUtil.java
  docs/lakehouse-iceberg-catalog.md
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java
Labels: need backport, branch-0.4

#2089 [#1313][#1471] feat(iceberg): Support struct column for iceberg
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ConvertUtil.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergType.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergTypeVisitor.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestConvertUtil.java
  docs/lakehouse-iceberg-catalog.md
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java
Labels: need backport, cherry-pick

#2076 [#2068] fix(web): fix data errors when update and create catalog
  web/lib/store/metalakes/index.js
Labels: need backport, branch-0.4

#2088 [#2074] fix(web): fix login input typing error
  web/app/ui/login/page.js
  web/lib/store/auth/index.js
Labels: need backport, branch-0.4

#2095 [#2068] fix(web): fix data errors when update and create catalog
  web/lib/store/metalakes/index.js
Labels: need backport, cherry-pick

#2096 [#2074] fix(web): fix login input typing error
  web/app/ui/login/page.js
  web/lib/store/auth/index.js
Labels: need backport, cherry-pick

#2097 [MINOR] docs: fix unparsed link
  docs/how-to-install.md
  docs/how-to-use-the-playground.md
Labels: need backport, branch-0.4

#2098 [MINOR] docs: fix unparsed link
  docs/how-to-install.md
  docs/how-to-use-the-playground.md
Labels: need backport, cherry-pick

#2094 [#1958] improvement(common): replace stream.peek with map
  common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java
Labels: need backport, branch-0.4

#2103 [#2102] fix the typo of license file name
  licenses/EPL1.0.txt
Labels: need backport, branch-0.4

#2105 [#2102] fix the typo of license file name
  licenses/EPL1.0.txt
Labels: need backport, cherry-pick

#2104 [#1958] improvement(common): replace stream.peek with map
  common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java
Labels: need backport, cherry-pick

#2107 [MINOR] docs: fix example of JDBC in OAS
  docs/open-api/tables.yaml
Labels: need backport, branch-0.4

#2112 [MINOR] docs: fix example of JDBC in OAS
  docs/open-api/tables.yaml
Labels: need backport, cherry-pick

#2120 [#2119] improvement(build): Update Docker latest tag for the branch which name is not the main
  .github/workflows/docker-image.yml
Labels: need backport, branch-0.4

#2122 [#2119] improvement(build): Update Docker latest tag for the branch which name is not the main
  .github/workflows/docker-image.yml
Labels: need backport, cherry-pick

#2125 [MINOR] docs: improve Gravitino document
  docs/docker-image-details.md
  docs/iceberg-rest-service.md
  docs/index.md
Labels: need backport, branch-0.4

#2126 [MINOR] fix docs
  docs/getting-started.md
  docs/manage-metadata-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
Labels: need backport, branch-0.4

#2129 [MINOR] fix docs
  docs/getting-started.md
  docs/manage-metadata-using-gravitino.md
  docs/table-partitioning-bucketing-sort-order-indexes.md
  docs/trino-connector/catalog-mysql.md
  docs/trino-connector/catalog-postgresql.md
Labels: need backport, cherry-pick

#2128 [MINOR] docs: improve Gravitino document
  docs/docker-image-details.md
  docs/iceberg-rest-service.md
  docs/index.md
Labels: need backport, cherry-pick

#2123 [MINOR] docs: Update the version of the OpenAPI document to 0.4.0
  docs/open-api/openapi.yaml
Labels: need backport, branch-0.4

#2130 [MINOR] docs: Update the version of the OpenAPI document to 0.4.0
  docs/open-api/openapi.yaml
Labels: need backport, cherry-pick

#2132 [MINOR] improve(docs): use html entities
  docs/manage-metadata-using-gravitino.md
  docs/manage-table-partition-using-gravitino.md
Labels: need backport, branch-0.4

#2134 [MINOR] improve(docs): use html entities
  docs/manage-metadata-using-gravitino.md
  docs/manage-table-partition-using-gravitino.md
Labels: need backport, cherry-pick

#2136 [#2118] docs(trino configuration): change gravitino.url to gravitino.uri
  docs/trino-connector/configuration.md
  docs/trino-connector/installation.md
Labels: need backport, branch-0.4

#2142 [#2118] docs(trino configuration): change gravitino.url to gravitino.uri
  docs/trino-connector/configuration.md
  docs/trino-connector/installation.md
Labels: need backport, cherry-pick

#2219 [MINOR] fix: typo in document
  docs/how-to-use-the-playground.md
Labels: branch-0.4

#2220 [MINOR] fix: typo in document
  docs/how-to-use-the-playground.md
Labels: cherry-pick

#2262 [#2194] Improvement(clients): Add NPE check for HTTPClient
  clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java
Labels: need backport, branch-0.4

#2277 [#2194] Improvement(clients): Add NPE check for HTTPClient
  clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java
Labels: need backport, cherry-pick

#2259 [#2121] fix(build): Fix publish bugs when publish module `clients` and `catalogs`
  build.gradle.kts
  catalogs/build.gradle.kts
  clients/build.gradle.kts
Labels: need backport, branch-0.4

#2283 [#2121] fix(build): Fix publish bugs when publish module `clients` and `catalogs`
  build.gradle.kts
  catalogs/build.gradle.kts
  clients/build.gradle.kts
Labels: need backport, cherry-pick

#2309 [#1735] fix(web): fix sorting and filtering of the metalakes table
  web/app/ui/MetalakeList.js
Labels: need backport, branch-0.4

#2313 [#1735] fix(web): fix sorting and filtering of the metalakes table
  web/app/ui/MetalakeList.js
Labels: need backport, cherry-pick

#2343 [#2324] improve(web): improve creating and updating user experience
  web/app/ui/CreateMetalakeDialog.js
  web/app/ui/metalakes/CreateCatalogDialog.js
  web/lib/store/metalakes/index.js
Labels: need backport, branch-0.4

#2360 [#2324] improve(web): improve creating and updating user experience
  web/app/ui/CreateMetalakeDialog.js
  web/app/ui/metalakes/CreateCatalogDialog.js
  web/lib/store/metalakes/index.js
Labels: need backport, cherry-pick

#2380 [#2378] fix(web): fix compatibility with safari
  web/app/ui/metalakes/page.js
Labels: need backport, branch-0.4

#2387 [#2378] fix(web): fix compatibility with safari
  web/app/ui/metalakes/page.js
Labels: need backport, cherry-pick

#2312 [#2099] fix(web): redirect to login page if token has expired
  web/app/ui/login/page.js
  web/lib/api/auth/index.js
  web/lib/layout/Logout.js
  web/lib/provider/session.js
  web/lib/store/auth/index.js
  web/lib/utils/axios/checkStatus.ts
  web/lib/utils/axios/index.ts
Labels: need backport, branch-0.4

#2374 [#2314] fix(postgresql): postgresql `public` schema should not be filtered in `listDatabases`
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Labels: need backport, branch-0.4

#2399 [#2314] fix(postgresql): postgresql `public` schema should not be filtered in `listDatabases`
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Labels: need backport, cherry-pick

#2398 [#2099] fix(web): redirect to login page if token has expired
  web/app/ui/login/page.js
  web/lib/api/auth/index.js
  web/lib/layout/Logout.js
  web/lib/provider/session.js
  web/lib/store/auth/index.js
  web/lib/utils/axios/checkStatus.ts
  web/lib/utils/axios/index.ts
Labels: need backport, cherry-pick
