Repository apache/gravitino, pull requests merged in 2024-05, with the labels that each got.

#3238 [#3237] fix(IT): use simple catalog name in `TrinoContainer`
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Labels: need backport, branch-0.5

#3242 [#3237] fix(IT): use simple catalog name in `TrinoContainer`
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Labels: need backport, cherry-pick

#3228 [#3227] fix(UT): tests run repeatedly
  core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java
Labels: need backport, branch-0.5

#3273 [#3227] fix(UT): tests run repeatedly
  core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java
Labels: need backport, cherry-pick

#3098 [#3037][#3086] improve(catalog-hadoop): Improve regexp in GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestGvfsBase.java
Labels: need backport, branch-0.5

#3267 [#3250] improve(catalog-jdbc-pg): Added missing @Override annotation
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Labels: need backport, branch-0.5

#3278 [#3250] improve(catalog-jdbc-pg): Added missing @Override annotation
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Labels: need backport, cherry-pick

#3276 [#3275] improvement(jdbc-doris): Filter system database like `information_schema` for Doris catalog.
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisDatabaseOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisDatabaseOperations.java
Labels: need backport, branch-0.5

#3284 [#3275] improvement(jdbc-doris): Filter system database like `information_schema` for Doris catalog.
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisDatabaseOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisDatabaseOperations.java
Labels: need backport, cherry-pick

#3277 [#3037][#3086] improve(catalog-hadoop): Improve regexp in GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestGvfsBase.java
Labels: need backport, cherry-pick

#3195 [#3066]: Improvement(IT): manage PostgreSQL containers in ContainerSuite
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion12IT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion14IT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion15IT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion16IT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/TestMultipleJDBCLoad.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/service/PostgreSqlService.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/TestMultipleJDBCLoad.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/MySQLContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/PGImageName.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/PostgreSQLContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/TestDatabaseName.java
Labels: branch-0.5

#3309 [#3293] feat(spark-connector): update kyuubi to 1.8.2
  gradle/libs.versions.toml
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java
Labels: cherry-pick

#3300 [#3299] fix(core): make catalog class non-shared
  core/src/main/java/com/datastrato/gravitino/utils/IsolatedClassLoader.java
Labels: need backport, branch-0.5

#3310 [#3299] fix(core): make catalog class non-shared
  core/src/main/java/com/datastrato/gravitino/utils/IsolatedClassLoader.java
Labels: need backport, cherry-pick

#3100 [#3092] fix(relational-entity-store): Return false when deleting throw a `NoSuchEntityException`
  core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalEntityStore.java
  core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
Labels: need backport, branch-0.5

#3312 [MINOR] refactor: update distribution parameters for Doris Test
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/integration/test/TestJdbcAbstractIT.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
Labels: need backport, cherry-pick

#3311 [#3092] fix(relational-entity-store): Return false when deleting throw a `NoSuchEntityException`
  core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalEntityStore.java
  core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
Labels: need backport, cherry-pick

#3221 [#2999][#2997] improvement(partition): add partition operation dispatcher
  core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java
  core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/TestTable.java
  core/src/test/java/com/datastrato/gravitino/TestTableOperations.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java
  server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
Labels: branch-0.5

#3294 [#3269] fix(jdbc-mysql): Solve DatabaseMetaData#getSchema return null cause list tables error on some jdbc 8.x driver
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisDriverIT.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlDriverIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
Labels: need backport, branch-0.5

#3315 [#2999][#2997] improvement(partition): add partition operation dispatcher
  core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java
  core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/PartitionOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/TestTable.java
  core/src/test/java/com/datastrato/gravitino/TestTableOperations.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java
  server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
Labels: cherry-pick

#3316 [#3269] fix(jdbc-mysql): Solve DatabaseMetaData#getSchema return null cause list tables error on some jdbc 8.x driver
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisDriverIT.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlDriverIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
Labels: need backport, cherry-pick

#3321 [#3295] fix(catalog-hive):The Hive Catalog Bug In Multiple Kerberized HMS
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  docs/apache-hive-catalog.md
Labels: need backport, branch-0.5

#3324 [#3295] fix(catalog-hive):The Hive Catalog Bug In Multiple Kerberized HMS
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  docs/apache-hive-catalog.md
Labels: need backport, cherry-pick

#3318 [#3320] fix(client): shadow slf4j for client-java-runtime
  clients/client-java-runtime/build.gradle.kts
Labels: branch-0.5

#3331 [#3320] fix(client): shadow slf4j for client-java-runtime
  clients/client-java-runtime/build.gradle.kts
Labels: cherry-pick

#3322 [#3319] fix(PyClient): ./gradlew test -PskipITs failed in python-client
  .github/workflows/python-integration-test.yml
  clients/client-python/build.gradle.kts
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/unittests/test_metalake.py
Labels: branch-0.5

#3314 [#2711] feat(filesystem): Support Kerberos client authentication in gvfs
  clients/filesystem-hadoop3/build.gradle.kts
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/KdcServerBase.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestKerberosClient.java
  docs/how-to-use-gvfs.md
Labels: branch-0.5

#3340 [#2711] feat(filesystem): Support Kerberos client authentication in gvfs
  clients/filesystem-hadoop3/build.gradle.kts
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/KdcServerBase.java
  clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestKerberosClient.java
  docs/how-to-use-gvfs.md
Labels: cherry-pick

#3332 [#3326] feat(jdbc-doris): output the alter status of table into the log
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
Labels: need backport, branch-0.5

#3338 [#3319] fix(PyClient): ./gradlew test -PskipITs failed in python-client
  .github/workflows/python-integration-test.yml
  clients/client-python/build.gradle.kts
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/unittests/test_metalake.py
Labels: cherry-pick

#3270 [#3292] fix(spark-connector): passing Gravitino catalog properties to spark connector
  docs/apache-hive-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/spark-connector/spark-catalog-hive.md
  docs/spark-connector/spark-catalog-iceberg.md
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/PropertiesConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
Labels: branch-0.5

#3357 [#3326] feat(jdbc-doris): output the alter status of table into the log
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
Labels: need backport, cherry-pick

#3189 [#2266] fix(partition): enable preassign partition when creating range and list partitioning table
  api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transform.java
  api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transforms.java
  api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/ListPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/RangePartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
  common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
  common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java
  docs/open-api/partitioning.yaml
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Labels: branch-0.5

#3243 [#2543] feat(spark-connector): support row-level operations to iceberg Table
  docs/spark-connector/spark-catalog-iceberg.md
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkCommonIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfo.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/ConnectorConstants.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/SparkHiveTable.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/utils/ConnectorUtil.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/utils/GravitinoTableInfoHelper.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/utils/TestConnectorUtil.java
Labels: branch-0.5

#3363 [#2266] fix(partition): enable preassign partition when creating range and list partitioning table
  api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transform.java
  api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transforms.java
  api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/ListPartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/RangePartitioningDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
  common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
  common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java
  docs/open-api/partitioning.yaml
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Labels: cherry-pick

#3358 [#3292] fix(spark-connector): passing Gravitino catalog properties to spark connector
  docs/apache-hive-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/spark-connector/spark-catalog-hive.md
  docs/spark-connector/spark-catalog-iceberg.md
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/PropertiesConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
Labels: cherry-pick

#3369 [#3205] improvement(client-python): Apply naming convention to client-python
  clients/client-python/gravitino/client/gravitino_admin_client.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/version_dto.py
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/gravitino/namespace.py
  clients/client-python/gravitino/typing.py
  clients/client-python/gravitino/utils/http_client.py
  clients/client-python/pylintrc
  clients/client-python/tests/integration/integration_test_env.py
Labels: branch-0.5

#3350 [#3347] improvement(jdbc-doris): support creating Doris table with partition
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
Labels: branch-0.5

#3380 [#3347] improvement(jdbc-doris): support creating Doris table with partition
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
Labels: cherry-pick

#3372 [#3205] improvement(client-python): Apply naming convention to client-python
  clients/client-python/gravitino/client/gravitino_admin_client.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/version_dto.py
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/gravitino/namespace.py
  clients/client-python/gravitino/typing.py
  clients/client-python/gravitino/utils/http_client.py
  clients/client-python/pylintrc
  clients/client-python/tests/integration/integration_test_env.py
Labels: cherry-pick

#2932 [#2230] feat(client-python): Add doc and support publishing Gravitino Python client to Pypi
  clients/client-python/.gitignore
  clients/client-python/README.md
  clients/client-python/build.gradle.kts
  clients/client-python/gravitino/__init__.py
  clients/client-python/gravitino/catalog/__init__.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/rest/__init__.py
  clients/client-python/requirements-dev.txt
  clients/client-python/requirements.txt
  clients/client-python/setup.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
  clients/client-python/tests/test_gravitino_client.py
  docs/assets/gravitino-python-client-introduction.png
  docs/how-to-use-python-client.md
  docs/how-to-use-the-playground.md
  docs/manage-fileset-metadata-using-gravitino.md
  docs/manage-metalake-using-gravitino.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.5

#3391 [#2230] feat(client-python): Add doc and support publishing Gravitino Python client to Pypi
  clients/client-python/.gitignore
  clients/client-python/README.md
  clients/client-python/build.gradle.kts
  clients/client-python/gravitino/__init__.py
  clients/client-python/gravitino/catalog/__init__.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/rest/__init__.py
  clients/client-python/requirements-dev.txt
  clients/client-python/requirements.txt
  clients/client-python/setup.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
  clients/client-python/tests/test_gravitino_client.py
  docs/assets/gravitino-python-client-introduction.png
  docs/how-to-use-python-client.md
  docs/how-to-use-the-playground.md
  docs/manage-fileset-metadata-using-gravitino.md
  docs/manage-metalake-using-gravitino.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: cherry-pick

#3384 [#3257] fix(web): add a default optional properties for fileset catalog
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/src/app/rootLayout/VersionView.js
  web/src/lib/utils/initial.js
Labels: branch-0.5

#3388 [#3291] fix(web): disable link dragging
  web/src/lib/styles/globals.css
Labels: branch-0.5

#3385 [#3285] fix(web): disable the metalake select with only one
  web/src/app/rootLayout/AppBar.js
Labels: need backport, branch-0.5

#3387 [#3386] fix(web): fix font family of the gravitino title
  web/LICENSE
  web/src/app/login/page.js
  web/src/app/rootLayout/AppBar.js
  web/src/lib/styles/globals.css
Labels: need backport, branch-0.5

#3398 [#3209] test(web): doris web e2e test (#3230)
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageDorisTest.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageKafkaTest.java
Labels: need backport, cherry-pick

#3301 [#3210] improve(web): add checking table properties to the web e2e test
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
  web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js
  web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
Labels: need backport, branch-0.5

#3393 [#3257] fix(web): add a default optional properties for fileset catalog
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/src/app/rootLayout/VersionView.js
  web/src/lib/utils/initial.js
Labels: cherry-pick

#3394 [#3291] fix(web): disable link dragging
  web/src/lib/styles/globals.css
Labels: cherry-pick

#3395 [#3285] fix(web): disable the metalake select with only one
  web/src/app/rootLayout/AppBar.js
Labels: need backport, cherry-pick

#3397 [#3386] fix(web): fix font family of the gravitino title
  web/LICENSE
  web/src/app/login/page.js
  web/src/app/rootLayout/AppBar.js
  web/src/lib/styles/globals.css
Labels: need backport, cherry-pick

#3401 [#3288] improve(web): rename the ASF providers to their correct names
  web/src/lib/utils/initial.js
Labels: branch-0.5

#3406 [#3288] improve(web): rename the ASF providers to their correct names
  web/src/lib/utils/initial.js
Labels: cherry-pick

#3417 [#3249] improvement(kafka-catalog): clarify error message and shorten timeout
  api/src/test/resources/log4j2.properties
  catalogs/catalog-hadoop/src/test/resources/log4j2.properties
  catalogs/catalog-hive/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java
  catalogs/catalog-kafka/src/main/resources/kafka.conf
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  catalogs/catalog-kafka/src/test/resources/log4j2.properties
  catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties
  clients/client-java/src/test/java/resources/log4j2.properties
  clients/client-java/src/test/resources/log4j2.properties
  common/src/test/java/resources/log4j2.properties
  core/src/test/resources/log4j2.properties
  dev/docker/trino/conf/log4j2.properties
  integration-test/src/test/resources/log4j2.properties
  server/src/test/resources/log4j2.properties
  spark-connector/spark-connector/src/test/resources/log4j2.properties
Labels: branch-0.5

#3421 [#3249] improvement(kafka-catalog): clarify error message and shorten timeout
  api/src/test/resources/log4j2.properties
  catalogs/catalog-hadoop/src/test/resources/log4j2.properties
  catalogs/catalog-hive/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java
  catalogs/catalog-kafka/src/main/resources/kafka.conf
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  catalogs/catalog-kafka/src/test/resources/log4j2.properties
  catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties
  clients/client-java/src/test/java/resources/log4j2.properties
  clients/client-java/src/test/resources/log4j2.properties
  common/src/test/java/resources/log4j2.properties
  core/src/test/resources/log4j2.properties
  dev/docker/trino/conf/log4j2.properties
  integration-test/src/test/resources/log4j2.properties
  server/src/test/resources/log4j2.properties
  spark-connector/spark-connector/src/test/resources/log4j2.properties
Labels: cherry-pick

#3400 [#3210] improve(web): add checking table properties to the web e2e test
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
  web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js
  web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
Labels: need backport, cherry-pick

#3416 [#3413] fix(web): fix logo error
  web/src/app/rootLayout/AppBar.js
Labels: need backport, branch-0.5

#3402 [#3248] fix(web): fix metalake list actions focus when using keyboard key:tab
  web/src/app/metalakes/TableBody.js
Labels: branch-0.5

#3258 [#3186] feat(spark-connector): Support Iceberg Spark Procedure
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
Labels: branch-0.5

#3436 [#3248] fix(web): fix metalake list actions focus when using keyboard key:tab
  web/src/app/metalakes/TableBody.js
Labels: cherry-pick

#3433 [#3413] fix(web): fix logo error
  web/src/app/rootLayout/AppBar.js
Labels: need backport, cherry-pick

#3265 [#3264] feat(spark-connector): Support Iceberg time travel in SQL queries
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
Labels: branch-0.5

#3467 [#3264] feat(spark-connector): Support Iceberg time travel in SQL queries
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
Labels: cherry-pick

#3423 [#3422]improve(doc, build): Set code tab switching params in the Python Client doc
  clients/client-python/MANIFEST.in
  clients/client-python/build.gradle.kts
  clients/client-python/setup.py
  docs/how-to-use-python-client.md
  docs/how-to-use-the-playground.md
Labels: branch-0.5

#3458 [MINOR] improve: Remove Duplicate condition in ScriptRunner
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/miniHMS/ScriptRunner.java
Labels: branch-0.5

#3469 [#3422]improve(doc, build): Set code tab switching params in the Python Client doc
  clients/client-python/MANIFEST.in
  clients/client-python/build.gradle.kts
  clients/client-python/setup.py
  docs/how-to-use-python-client.md
  docs/how-to-use-the-playground.md
Labels: cherry-pick

#3471 [MINOR] improve: Remove Duplicate condition in ScriptRunner
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/miniHMS/ScriptRunner.java
Labels: cherry-pick

#3474 [#3128] bugfix(hive): fix order of sort column for ascending sort direction should be 1
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
Labels: branch-0.5

#3482 [#3128] bugfix(hive): fix order of sort column for ascending sort direction should be 1
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
Labels: cherry-pick

#2364 [#2226] dev(docker): Add a Hive with Kerberos mode Docker image
  .github/workflows/docker-image.yml
  build.gradle.kts
  dev/docker/build-docker.sh
  dev/docker/kerberos-hive/Dockerfile
  dev/docker/kerberos-hive/check-status.sh
  dev/docker/kerberos-hive/core-site.xml
  dev/docker/kerberos-hive/hadoop-env.sh
  dev/docker/kerberos-hive/hdfs-site.xml
  dev/docker/kerberos-hive/hive-dependency.sh
  dev/docker/kerberos-hive/hive-site.xml
  dev/docker/kerberos-hive/kadm5.acl
  dev/docker/kerberos-hive/kdc.conf
  dev/docker/kerberos-hive/krb5.conf
  dev/docker/kerberos-hive/mapred-site.xml
  dev/docker/kerberos-hive/start.sh
  dev/docker/kerberos-hive/yarn-env.sh
  dev/docker/kerberos-hive/yarn-site.xml
  docs/docker-image-details.md
Labels: branch-0.5

#3488 [#2226] dev(docker): Add a Hive with Kerberos mode Docker image
  .github/workflows/docker-image.yml
  build.gradle.kts
  dev/docker/build-docker.sh
  dev/docker/kerberos-hive/Dockerfile
  dev/docker/kerberos-hive/check-status.sh
  dev/docker/kerberos-hive/core-site.xml
  dev/docker/kerberos-hive/hadoop-env.sh
  dev/docker/kerberos-hive/hdfs-site.xml
  dev/docker/kerberos-hive/hive-dependency.sh
  dev/docker/kerberos-hive/hive-site.xml
  dev/docker/kerberos-hive/kadm5.acl
  dev/docker/kerberos-hive/kdc.conf
  dev/docker/kerberos-hive/krb5.conf
  dev/docker/kerberos-hive/mapred-site.xml
  dev/docker/kerberos-hive/start.sh
  dev/docker/kerberos-hive/yarn-env.sh
  dev/docker/kerberos-hive/yarn-site.xml
  docs/docker-image-details.md
Labels: cherry-pick

#3487 [#3484] improvement(docker): Remove unused yarn configuration from Hive docker file
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-lakehouse-iceberg/build.gradle.kts
  dev/docker/hive/Dockerfile
  dev/docker/hive/mapred-site.xml
  dev/docker/hive/yarn-env.sh
  dev/docker/hive/yarn-site.xml
  docs/docker-image-details.md
  integration-test/build.gradle.kts
  integration-test/trino-it/docker-compose.yaml
Labels: branch-0.5

#3477 [#1761] fix(mysql)clarify `timestamp` and `datetime` type convert
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java
Labels: branch-0.5

#3493 [#1761] fix(mysql)clarify `timestamp` and `datetime` type convert
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java
Labels: cherry-pick

#3492 [#3484] improvement(docker): Remove unused yarn configuration from Hive docker file
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-lakehouse-iceberg/build.gradle.kts
  dev/docker/hive/Dockerfile
  dev/docker/hive/mapred-site.xml
  dev/docker/hive/yarn-env.sh
  dev/docker/hive/yarn-site.xml
  docs/docker-image-details.md
  integration-test/build.gradle.kts
  integration-test/trino-it/docker-compose.yaml
Labels: cherry-pick

#3494 [#3342] feat(core): Refactor the role and privilege model
  api/src/main/java/com/datastrato/gravitino/authorization/Privilege.java
  api/src/main/java/com/datastrato/gravitino/authorization/Privileges.java
  api/src/main/java/com/datastrato/gravitino/authorization/Role.java
  api/src/main/java/com/datastrato/gravitino/authorization/SecurableObject.java
  api/src/main/java/com/datastrato/gravitino/authorization/SecurableObjects.java
  api/src/test/java/com/datastrato/gravitino/authorization/TestSecurableObjects.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/DTOConverters.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoAdminClient.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRole.java
  common/src/main/java/com/datastrato/gravitino/dto/authorization/PrivilegeDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/authorization/RoleDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/authorization/SecurableObjectDTO.java
  common/src/main/java/com/datastrato/gravitino/dto/requests/RoleCreateRequest.java
  common/src/main/java/com/datastrato/gravitino/dto/responses/RoleResponse.java
  common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
  common/src/test/java/com/datastrato/gravitino/dto/responses/TestResponses.java
  core/src/main/java/com/datastrato/gravitino/authorization/AccessControlManager.java
  core/src/main/java/com/datastrato/gravitino/authorization/RoleManager.java
  core/src/main/java/com/datastrato/gravitino/meta/RoleEntity.java
  core/src/main/java/com/datastrato/gravitino/proto/RoleEntitySerDe.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/po/RolePO.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java
  core/src/test/java/com/datastrato/gravitino/meta/TestEntity.java
  core/src/test/java/com/datastrato/gravitino/proto/TestEntityProtoSerDe.java
  core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
  core/src/test/java/com/datastrato/gravitino/storage/memory/TestMemoryEntityStore.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/resources/h2/schema-h2.sql
  meta/src/main/proto/gravitino_meta.proto
  scripts/mysql/schema-0.5.0-mysql.sql
  server/src/main/java/com/datastrato/gravitino/server/web/rest/RoleOperations.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestRoleOperations.java
Labels: cherry-pick

#3268 refactor(dev/docker/hive): shrink hive Docker image size by 420MB
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-lakehouse-iceberg/build.gradle.kts
  dev/docker/build-docker.sh
  dev/docker/hive/Dockerfile
  dev/docker/hive/start.sh
  docs/docker-image-details.md
  integration-test/build.gradle.kts
Labels: branch-0.5

#3504 [#3188] feat(core): Clean user,group and role entity in RelationalGarbageCollector
  core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/utils/SessionUtils.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Labels: cherry-pick

#2928 [#2921] fix(catalog-lakehouse-iceberg): Add width param to bucket and truncate functions in Gravitino SortOrder
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergSortOrder.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergSortOrder.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestBaseConvert.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestFromIcebergSortOrder.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestToIcebergSortOrder.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
Labels: branch-0.5

#3507 [#3202] improve(web): modified rules for create name field
  web/src/app/metalakes/CreateMetalakeDialog.js
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/src/lib/utils/regex.js
Labels: need backport, branch-0.5

#3435 [#3432] improvement(test): Add kerberos authentication IT for HDFS cluster
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HDFSKerberosIT.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/BaseContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
Labels: upload log, branch-0.5

#3518 [#3202] improve(web): modified rules for create name field
  web/src/app/metalakes/CreateMetalakeDialog.js
  web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/src/lib/utils/regex.js
Labels: need backport, cherry-pick

#3307 [#3305] test(spark-connector): move spark connector integration test from integration-test module to spark-connector
  gradle/libs.versions.toml
  integration-test/build.gradle.kts
  spark-connector/spark-connector-runtime/build.gradle.kts
  spark-connector/spark-connector/build.gradle.kts
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTransformConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkEnvIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/hive/SparkHiveCatalogIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogHiveBackendIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogRestBackendIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkMetadataColumnInfo.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkTableInfo.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkTableInfoChecker.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkUtilIT.java
Labels: branch-0.5

#3522 [#3521] fix(client-python): Fix `hash()` function with multiple variables issue in `name_identitifer`
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/tests/unittests/test_name_identifier.py
Labels: branch-0.5

#3510 [#3202] improvement(core): add name spec for catalog and metalake
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
  core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java
  core/src/main/java/com/datastrato/gravitino/metalake/MetalakeManager.java
  core/src/main/java/com/datastrato/gravitino/metalake/MetalakeNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/metalake/TestMetalakeNormalizeDispatcher.java
Labels: branch-0.5

#3509 [#3058] improvement(client-python): Correct type specification of create_fileset function
  clients/client-python/gravitino/catalog/fileset_catalog.py
Labels: branch-0.5

#3532 [#3521] fix(client-python): Fix `hash()` function with multiple variables issue in `name_identitifer`
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/tests/unittests/test_name_identifier.py
Labels: cherry-pick

#3534 [#3202] improvement(core): add name spec for catalog and metalake
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
  core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java
  core/src/main/java/com/datastrato/gravitino/metalake/MetalakeManager.java
  core/src/main/java/com/datastrato/gravitino/metalake/MetalakeNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/metalake/TestMetalakeNormalizeDispatcher.java
Labels: cherry-pick

#3535 [#3058] improvement(client-python): Correct type specification of create_fileset function
  clients/client-python/gravitino/catalog/fileset_catalog.py
Labels: cherry-pick

#3538 [#3336] improvement(test): make docker detection failure error messages more clear
  build.gradle.kts
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
Labels: branch-0.5

#3511 [#2962] feat(catalog-lakehouse-iceberg): Add reserved properties to Iceberg Table Properties in Gravitino
  LICENSE
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTablePropertiesMetadata.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/DescribeIcebergSortOrderVisitor.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergTablePropertiesUtil.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
Labels: branch-0.5

#3542 [#3336] improvement(test): make docker detection failure error messages more clear
  build.gradle.kts
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
Labels: cherry-pick

#3543 [#2962] feat(catalog-lakehouse-iceberg): Add reserved properties to Iceberg Table Properties in Gravitino
  LICENSE
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTablePropertiesMetadata.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/DescribeIcebergSortOrderVisitor.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergTablePropertiesUtil.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
Labels: cherry-pick

#3549 [#3548] fix(dev): Create a new image to add a principal for Gravitino web server and fix several bugs about proxy users
  dev/docker/kerberos-hive/core-site.xml
  dev/docker/kerberos-hive/start.sh
  docs/docker-image-details.md
Labels: branch-0.5

#3539 [#3396] feat(spark-connector): remove iceberg runtime from spark-connector jar
  docs/spark-connector/spark-catalog-iceberg.md
  docs/spark-connector/spark-connector.md
  spark-connector/spark-connector-runtime/build.gradle.kts
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/GravitinoSparkConfig.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkEnvIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/plugin/TestGravitinoDriverPlugin.java
Labels: branch-0.5

#3551 [#3548] fix(dev): Create a new image to add a principal for Gravitino web server and fix several bugs about proxy users
  dev/docker/kerberos-hive/core-site.xml
  dev/docker/kerberos-hive/start.sh
  docs/docker-image-details.md
Labels: cherry-pick

#3553 [#3396] feat(spark-connector): remove iceberg runtime from spark-connector jar
  docs/spark-connector/spark-catalog-iceberg.md
  docs/spark-connector/spark-connector.md
  spark-connector/spark-connector-runtime/build.gradle.kts
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/GravitinoSparkConfig.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkEnvIT.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/plugin/TestGravitinoDriverPlugin.java
Labels: cherry-pick

#3512 [#3009] improve(web): improve the user experience of refreshing the oauth token
  web/src/lib/provider/session.js
  web/src/lib/store/auth/index.js
  web/src/lib/utils/axios/checkStatus.ts
  web/src/lib/utils/axios/index.ts
Labels: need backport, branch-0.5

#3544 [MINOR] Add logos in PNG format with different colors
  web/public/icons/gravitino.png
  web/public/icons/gravitino_black.png
  web/public/icons/gravitino_white.png
Labels: branch-0.5

#3557 [MINOR] Add logos in PNG format with different colors
  web/public/icons/gravitino.png
  web/public/icons/gravitino_black.png
  web/public/icons/gravitino_white.png
Labels: cherry-pick

#3556 [#3009] improve(web): improve the user experience of refreshing the oauth token
  web/src/lib/provider/session.js
  web/src/lib/store/auth/index.js
  web/src/lib/utils/axios/checkStatus.ts
  web/src/lib/utils/axios/index.ts
Labels: need backport, cherry-pick

#3562 [#3561] improvement(client-python): Fix redefined-builtin Pylint rule for client-python
  clients/client-python/gravitino/api/catalog_change.py
  clients/client-python/gravitino/api/fileset_change.py
  clients/client-python/gravitino/api/metalake_change.py
  clients/client-python/gravitino/api/schema_change.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/client/gravitino_client.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/catalog_dto.py
  clients/client-python/gravitino/dto/dto_converters.py
  clients/client-python/gravitino/dto/requests/catalog_create_request.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/requests/fileset_create_request.py
  clients/client-python/gravitino/dto/requests/fileset_update_request.py
  clients/client-python/gravitino/dto/requests/metalake_update_request.py
  clients/client-python/gravitino/dto/requests/schema_update_request.py
  clients/client-python/pylintrc
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_schema.py
Labels: branch-0.5

#3565 [#3564] fix(client): spark connector failed to start in real spark3.3 envriment
  clients/client-java-runtime/build.gradle.kts
  core/src/main/java/com/datastrato/gravitino/connector/PropertyEntry.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/metadata/GravitinoCatalog.java
Labels: branch-0.5

#3568 [#3561] improvement(client-python): Fix redefined-builtin Pylint rule for client-python
  clients/client-python/gravitino/api/catalog_change.py
  clients/client-python/gravitino/api/fileset_change.py
  clients/client-python/gravitino/api/metalake_change.py
  clients/client-python/gravitino/api/schema_change.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/client/gravitino_client.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/catalog_dto.py
  clients/client-python/gravitino/dto/dto_converters.py
  clients/client-python/gravitino/dto/requests/catalog_create_request.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/requests/fileset_create_request.py
  clients/client-python/gravitino/dto/requests/fileset_update_request.py
  clients/client-python/gravitino/dto/requests/metalake_update_request.py
  clients/client-python/gravitino/dto/requests/schema_update_request.py
  clients/client-python/pylintrc
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_schema.py
Labels: cherry-pick

#3569 [#3564] fix(client): spark connector failed to start in real spark3.3 envriment
  clients/client-java-runtime/build.gradle.kts
  core/src/main/java/com/datastrato/gravitino/connector/PropertyEntry.java
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/metadata/GravitinoCatalog.java
Labels: cherry-pick

#3573 [#3571] fix(CI): Skip cron job in fork repo by default.
  .github/workflows/cron-integration-test.yml
Labels: branch-0.5

#3525 [#3489] improvement(hive-catalog): Add user authentication e2e test for Hive catalog
  .github/workflows/backend-integration-test.yml
  api/src/main/java/com/datastrato/gravitino/rel/expressions/sorts/SortOrders.java
  bin/gravitino.sh
  catalogs/catalog-hive/build.gradle.kts
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogPropertiesMeta.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveProxyPlugin.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/HiveUserAuthenticationIT.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/ProxyCatalogHiveIT.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/MiniGravitino.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/GravitinoITUtils.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/KerberosOperationsIT.java
Labels: branch-0.5

#3490 [#3137] fix(spark-connector): change table comment though table properties
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
Labels: branch-0.5

#3592 [#3137] fix(spark-connector): change table comment though table properties
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
Labels: cherry-pick

#3591 [#3152] feat(core): using time sliding window to record timer metrics
  common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  core/src/main/java/com/datastrato/gravitino/Configs.java
  core/src/main/java/com/datastrato/gravitino/metrics/source/MetricsSource.java
  core/src/test/java/com/datastrato/gravitino/metrics/TestMetricsSystem.java
  core/src/test/java/com/datastrato/gravitino/metrics/source/TestMetricsSource.java
  docs/gravitino-server-config.md
  server-common/src/main/java/com/datastrato/gravitino/server/web/HttpServerMetricsSource.java
Labels: cherry-pick

#3599 [#3598] fix(common): fix compatibility of type serde
  api/src/main/java/com/datastrato/gravitino/rel/types/Types.java
  common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
  common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java
Labels: branch-0.5

#3603 [#3598] fix(common): fix compatibility of type serde
  api/src/main/java/com/datastrato/gravitino/rel/types/Types.java
  common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
  common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java
Labels: cherry-pick

#3559 [#3558] fix(client-python): specified tests packages version
  clients/client-python/requirements-dev.txt
Labels: branch-0.5

#3619 [#3593] fix(web): replace the Alata font family with Roboto whose license is under the Apache Software License 2.0
  web/LICENSE
  web/src/app/login/page.js
  web/src/app/rootLayout/AppBar.js
Labels: branch-0.5

#3608 [#3555] feat(spark-connector): support multi scala version
  .github/workflows/spark-integration-test.yml
  settings.gradle.kts
  spark-connector/spark-common/build.gradle.kts
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTransformConverter.java
Labels: branch-0.5

#3613 [#3558] fix(client-python): specified tests packages version
  clients/client-python/requirements-dev.txt
Labels: cherry-pick

#3596 [#3595] Improvement(spark-connector): update spark-iceberg connector document
  docs/spark-connector/spark-catalog-iceberg.md
Labels: branch-0.5

#3628 [#3595] Improvement(spark-connector): update spark-iceberg connector document
  docs/spark-connector/spark-catalog-iceberg.md
Labels: cherry-pick

#3624 [#3593] fix(web): replace the Alata font family with Roboto whose license is under the Apache Software License 2.0
  web/LICENSE
  web/src/app/login/page.js
  web/src/app/rootLayout/AppBar.js
Labels: cherry-pick

#3222 [#2434] Improvement: if DropXXX success, return true, if not exists return false
  api/src/main/java/com/datastrato/gravitino/SupportsMetalakes.java
  api/src/main/java/com/datastrato/gravitino/rel/SupportsPartitions.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveSchema.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTableOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/DatabaseOperation.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/TableOperation.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/integration/test/TestJdbcAbstractIT.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteDatabaseOperations.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/TestJdbcDatabaseOperations.java
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/TestJdbcTableOperations.java
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisExceptionConverter.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/converter/TestDorisExceptionConverter.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/AuditCatalogMysqlIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/PostgreSqlTableOperationsIT.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoAdminClient.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoClient.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoMetalake.java
  clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java
  core/src/main/java/com/datastrato/gravitino/catalog/SupportsCatalogs.java
  core/src/main/java/com/datastrato/gravitino/metalake/SupportsMetalakes.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTableOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestTopicOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/metalake/TestMetalakeManager.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/AuditIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/MetalakeIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/filesystem/hadoop/GravitinoVirtualFileSystemIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestFilesetOperations.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestMetalakeOperations.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
Labels: branch-0.5

#3617 [#3579] fix(license): mention license for svg files
  web/LICENSE
  web/src/lib/icons/svg/doris.svg
  web/src/lib/icons/svg/hive.svg
Labels: branch-0.5

#3639 [#3638] Fix UT HadoopUserImpersonationIT fails occasionally
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
Labels: branch-0.5

#3647 [#3646] doc: Add the Docker image change log for 0.5.1
  docs/docker-image-details.md
Labels: need backport, branch-0.5

#3651 [#3646] doc: Add the Docker image change log for 0.5.1
  docs/docker-image-details.md
Labels: need backport, cherry-pick

#3645 [#3648] improvement(CI): skip unnecessary tests in backendIT
  .github/workflows/backend-integration-test.yml
Labels: branch-0.5

#3586 [#3583] fix(docker-image): Fix the problem that kerberized HDFS datanode start fail occasionally
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  dev/docker/kerberos-hive/start.sh
  docs/docker-image-details.md
Labels: branch-0.5

#3653 [#3648] improvement(CI): skip unnecessary tests in backendIT
  .github/workflows/backend-integration-test.yml
Labels: cherry-pick

#3614 [#3660] docs(spark-connector): add multi spark and scala version for spark connector doc
  docs/how-to-build.md
  docs/spark-connector/spark-connector.md
Labels: branch-0.5

#3656 [#3660] docs(spark-connector): add multi spark and scala version for spark connector doc
  docs/how-to-build.md
  docs/spark-connector/spark-connector.md
Labels: cherry-pick

#3611 [#3244] refactor(core, catalogs): decouple CatalogOperations and HasPropertyMetadata
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalog.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalog.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalog.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalog.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/MySQLProtocolCompatibleCatalogOperations.java
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalog.java
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalog.java
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSQLCatalogOperations.java
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSqlCatalog.java
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalog.java
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergSchema.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
  core/src/main/java/com/datastrato/gravitino/connector/CatalogInfo.java
  core/src/main/java/com/datastrato/gravitino/connector/CatalogOperations.java
  core/src/test/java/com/datastrato/gravitino/TestCatalog.java
  core/src/test/java/com/datastrato/gravitino/catalog/DummyCatalogOperations.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogManager.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestOperationDispatcher.java
  core/src/test/java/com/datastrato/gravitino/connector/TestCatalogOperations.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestCatalog.java
  web/src/app/metalakes/metalake/MetalakeView.js
Labels: branch-0.5

#3633 [MINOR] refactor(tests): Remove non-IT tests from IT package
  catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/TestJdbc.java
  catalogs/catalog-jdbc-doris/build.gradle.kts
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/operation/TestDoris.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/operation/TestDorisDatabaseOperations.java
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/operation/TestDorisTableOperations.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysql.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlDatabaseOperations.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/PostgreSqlTableOperationsIT.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/operation/TestPostgreSql.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/operation/TestPostgreSqlSchemaOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/operation/TestPostgreSqlTableOperations.java
Labels: branch-0.5

#3657 [#3244] refactor(core, catalogs): decouple CatalogOperations and HasPropertyMetadata
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalog.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalog.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalog.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalog.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/MySQLProtocolCompatibleCatalogOperations.java
  catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalog.java
  catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalog.java
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSQLCatalogOperations.java
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSqlCatalog.java
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalog.java
  catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergSchema.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
  core/src/main/java/com/datastrato/gravitino/connector/CatalogInfo.java
  core/src/main/java/com/datastrato/gravitino/connector/CatalogOperations.java
  core/src/test/java/com/datastrato/gravitino/TestCatalog.java
  core/src/test/java/com/datastrato/gravitino/TestCatalogOperations.java
  core/src/test/java/com/datastrato/gravitino/catalog/DummyCatalogOperations.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestBaseCatalog.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogManager.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java
  core/src/test/java/com/datastrato/gravitino/catalog/TestOperationDispatcher.java
  server/src/test/java/com/datastrato/gravitino/server/web/rest/TestCatalog.java
  web/src/app/metalakes/metalake/MetalakeView.js
Labels: cherry-pick

#3655 [#3583] fix(docker-image): Fix the problem that kerberized HDFS datanode start fail occasionally
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hive/build.gradle.kts
  dev/docker/kerberos-hive/start.sh
  docs/docker-image-details.md
Labels: cherry-pick

#3666 [Minor] docs(all): Change Java doc version from 0.5.0 to 0.5.1
  docs/index.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.5

#3552 [#3537] improvement(hadooop-catalog): Add e2e user authentication tests for Hadoop catalog.
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/KerberosClient.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserAuthenticationIT.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
Labels: branch-0.5

#3667 [Minor] docs(all): Change Java doc version from 0.5.0 to 0.5.1
  docs/index.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: cherry-pick

#3659 [#3658] docs(hadoop-catalog): Add document about user authentication for Hadoop catalog
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/AuthenticationConfig.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/KerberosConfig.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserAuthenticationIT.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
  docs/hadoop-catalog.md
Labels: branch-0.5

#3672 [#3673] fix(core): avoid to initialize catalog ops when closing catalog
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
Labels: branch-0.5

#3678 [#3658] docs(hadoop-catalog): Add document about user authentication for Hadoop catalog
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/AuthenticationConfig.java
  catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/KerberosConfig.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserAuthenticationIT.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
  docs/hadoop-catalog.md
Labels: cherry-pick

#3679 [#3673] fix(core): avoid to initialize catalog ops when closing catalog
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
Labels: cherry-pick

#3654 [#3649] feat(client): remove log4j impl from client-java-runtime
  clients/client-java-runtime/build.gradle.kts
  clients/client-java/build.gradle.kts
  clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClientBase.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java
  clients/filesystem-hadoop3/build.gradle.kts
  common/build.gradle.kts
  core/src/main/java/com/datastrato/gravitino/Config.java
  core/src/main/java/com/datastrato/gravitino/config/ConfigBuilder.java
  core/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  core/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java
  core/src/test/java/com/datastrato/gravitino/TestConfig.java
  core/src/test/java/com/datastrato/gravitino/config/TestConfigEntry.java
  core/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java
Labels: branch-0.5

#3682 [#3680] docs(trino-connector): Update Trino connector doc for using Trino dynamic catalog
  docs/trino-connector/configuration.md
  docs/trino-connector/development.md
  docs/trino-connector/installation.md
  docs/trino-connector/requirements.md
  docs/trino-connector/trino-connector.md
Labels: branch-0.5

#3684 [#3683] fix(docker): Update Trino docker image to Trino-435
  dev/docker/trino/Dockerfile
  dev/docker/trino/conf/config.properties
  dev/docker/trino/conf/jvm.config
  docs/docker-image-details.md
Labels: branch-0.5

#3686 [MINOR] improvement(log): add log for server
  server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/FilesetOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/MetalakeOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/SchemaOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/TableOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/TopicOperations.java
Labels: branch-0.5

#3695 [MINOR] improvement(log): add log for server
  server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/FilesetOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/MetalakeOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/SchemaOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/TableOperations.java
  server/src/main/java/com/datastrato/gravitino/server/web/rest/TopicOperations.java
Labels: cherry-pick

#3689 [#3546] fix(core): overwrite the relationship when insert overwrite user and group
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Labels: need backport, branch-0.5

#3697 [#3546] fix(core): overwrite the relationship when insert overwrite user and group
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Labels: need backport, cherry-pick
