Repository apache/gravitino, pull requests merged in 2024-10, with the labels that each got.

#5021 [#4903] feat(core,server): Support to grant or revoke privileges for a role
  api/src/main/java/org/apache/gravitino/authorization/SecurableObjects.java
  api/src/main/java/org/apache/gravitino/exceptions/IllegalPrivilegeException.java
  clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
  clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestPermission.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
  common/src/main/java/org/apache/gravitino/dto/requests/PrivilegeGrantRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/PrivilegeRevokeRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/RoleCreateRequest.java
  common/src/main/java/org/apache/gravitino/dto/responses/ErrorResponse.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
  core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/RoleMetaBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/SecurableObjectBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SecurableObjectPostgreSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  server/src/main/java/org/apache/gravitino/server/web/Utils.java
  server/src/main/java/org/apache/gravitino/server/web/mapper/JsonMappingExceptionMapper.java
  server/src/main/java/org/apache/gravitino/server/web/mapper/JsonParseExceptionMapper.java
  server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java
  server/src/main/java/org/apache/gravitino/server/web/rest/PermissionOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestPermissionOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Labels: branch-0.6

#5080 [MINOR] improvement(release): improve release script
  dev/release/release-build.sh
  dev/release/release-tag.sh
  dev/release/release-util.sh
Labels: branch-0.6

#5084 [#5082] fix(catalog): fix clean bug after create catalog failed
  build.gradle.kts
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
  core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
  core/src/test/java/org/apache/gravitino/catalog/TestCatalogManager.java
Labels: branch-0.6

#5102 [#5101] improvement(docs): Fix the document error about access control
  docs/docker-image-details.md
  docs/security/access-control.md
Labels: branch-0.6

#5107 [MINOR] fix(docs): change version info from 0.6.0 to 0.6.0-incubating
  MAINTAINERS.md
  docs/apache-hive-catalog.md
  docs/gravitino-server-config.md
  docs/hadoop-catalog.md
  docs/how-to-use-relational-backend-storage.md
  docs/iceberg-rest-service.md
  docs/jdbc-doris-catalog.md
  docs/jdbc-mysql-catalog.md
  docs/jdbc-postgresql-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/lakehouse-paimon-catalog.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.6

#5207 [#5114] Improvement:use incubating version in docs
  docs/apache-hive-catalog.md
  docs/flink-connector/flink-catalog-hive.md
  docs/flink-connector/flink-connector.md
  docs/hadoop-catalog.md
  docs/how-to-use-gvfs.md
  docs/iceberg-rest-service.md
  docs/security/authorization-pushdown.md
  docs/security/how-to-authenticate.md
  docs/spark-connector/spark-catalog-iceberg.md
  docs/spark-connector/spark-integration-test.md
Labels: branch-0.7

#5234 [#5213] Improvement: Fix the flaky test
  catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestFetchFileUtils.java
Labels: branch-0.7

#5223 [#5168][#5169][#5170] Feature(web): Add ui support for creating, editing, viewing, and deleting fileset
  web/web/src/app/metalakes/metalake/rightContent/CreateFilesetDialog.js
  web/web/src/app/metalakes/metalake/rightContent/RightContent.js
  web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
  web/web/src/lib/api/filesets/index.js
  web/web/src/lib/store/metalakes/index.js
Labels: branch-0.7

#5186 [#4599][#4809] feat(core): Add tag support for column
  api/src/main/java/org/apache/gravitino/rel/Column.java
  api/src/test/java/org/apache/gravitino/TestMetadataObjects.java
  catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/integration/test/HudiCatalogHMSIT.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestCatalogUtils.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericColumn.java
  clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericTag.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestRelationalCatalog.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableColumnMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableColumnSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TableColumnBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/TableColumnMetaService.java
  core/src/main/java/org/apache/gravitino/tag/TagManager.java
  core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java
  core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
  core/src/main/java/org/apache/gravitino/utils/NamespaceUtil.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestTableColumnMetaService.java
  core/src/test/java/org/apache/gravitino/tag/TestTagManager.java
  core/src/test/java/org/apache/gravitino/utils/TestMetadataObjectUtil.java
  core/src/test/java/org/apache/gravitino/utils/TestNameIdentifierUtil.java
  docs/manage-tags-in-gravitino.md
  docs/open-api/openapi.yaml
  docs/open-api/tags.yaml
Labels: need backport, branch-0.7

#5235 [#4817] fix(core): Fix unexpected tag delete issue
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TagMetadataObjectRelBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetadataObjectRelPostgreSQLProvider.java
Labels: need backport, branch-0.7

#5253 [#5252] fix(catalog): fix disable catalog miss invalidate cache
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
  core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
Labels: branch-0.7

#5224 [#5068] feat(core): support GCS token provider
  LICENSE.bin
  api/src/main/java/org/apache/gravitino/credential/GCSTokenCredential.java
  bundles/gcp-bundle/build.gradle.kts
  bundles/gcp-bundle/src/main/java/org/apache/gravitino/gcs/credential/GCSTokenProvider.java
  bundles/gcp-bundle/src/main/resources/META-INF/services/org.apache.gravitino.credential.CredentialProvider
  bundles/gcp-bundle/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
  catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
  common/src/main/java/org/apache/gravitino/credential/CredentialPropertyUtils.java
  core/src/main/java/org/apache/gravitino/credential/config/GCSCredentialConfig.java
  gradle/libs.versions.toml
  iceberg/iceberg-rest-server/build.gradle.kts
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTGCSIT.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTJdbcCatalogIT.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTServiceBaseIT.java
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/BaseIT.java
  integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/ITUtils.java
  settings.gradle.kts
Labels: branch-0.7

#5218 [#5217] docs(metalake-catalog): refine docs for deleting metalake and catalog
  docs/manage-fileset-metadata-using-gravitino.md
  docs/manage-messaging-metadata-using-gravitino.md
  docs/manage-metalake-using-gravitino.md
  docs/manage-relational-metadata-using-gravitino.md
  docs/open-api/catalogs.yaml
  docs/open-api/metalakes.yaml
  docs/open-api/openapi.yaml
Labels: branch-0.7

#5268 [#4913] fix(API): fix call bucketTransform arguments failed
  api/src/main/java/org/apache/gravitino/rel/expressions/transforms/Transforms.java
  api/src/test/java/org/apache/gravitino/rel/TestTransforms.java
Labels: branch-0.7

#5090 [MINOR] improvement(release): update docs version when release
  dev/release/release-build.sh
  dev/release/release-tag.sh
  dev/release/update-java-doc-version.sh
Labels: branch-0.7

#5271 [#4641] fix(web): improvement scroll bar on the catalog detail page ellipsis display
  web/web/src/components/DetailsDrawer.js
Labels: branch-0.7

#5121 [#4968] improvement(api): Unify the modification behavior of the comment field
  api/src/main/java/org/apache/gravitino/file/FilesetChange.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  catalogs/catalog-kafka/src/test/java/org/apache/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/MetalakeIT.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
  clients/client-python/gravitino/api/fileset_change.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/requests/fileset_update_request.py
  clients/client-python/gravitino/dto/requests/metalake_update_request.py
  clients/client-python/tests/integration/test_catalog.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_metalake.py
  common/src/main/java/org/apache/gravitino/dto/requests/CatalogUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/FilesetUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/MetalakeUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/TableUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/TagUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/TopicUpdateRequest.java
  core/src/test/java/org/apache/gravitino/catalog/TestFilesetOperationDispatcher.java
  docs/manage-fileset-metadata-using-gravitino.md
  server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
Labels: branch-0.7

#5283 [Minor] fix spelling in error messages
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
Labels: branch-0.7

#5284 [Minor] fix spelling th -> the
  api/src/main/java/org/apache/gravitino/MetadataObject.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObject.java
Labels: branch-0.7

#5290 [Minor] Update playground doc
  docs/how-to-use-the-playground.md
Labels: branch-0.7

#5250 [#5206] UI (metalake, catalog): Web UI add disable/enable metalake/catalog button
  web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java
  web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
  web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java
  web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java
  web/web/src/app/metalakes/CreateMetalakeDialog.js
  web/web/src/app/metalakes/TableBody.js
  web/web/src/app/metalakes/metalake/MetalakeTree.js
  web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
  web/web/src/components/ConfirmDeleteDialog.js
  web/web/src/lib/api/catalogs/index.js
  web/web/src/lib/api/metalakes/index.js
  web/web/src/lib/store/metalakes/index.js
  web/web/src/lib/utils/axios/Axios.js
Labels: branch-0.7

#5286 [#5261] feat(oceanbase-catalog): Add IT for OceanBase JDBC catalog
  build.gradle.kts
  catalogs/catalog-jdbc-oceanbase/build.gradle.kts
  catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/integration/test/CatalogOceanBaseIT.java
  catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/integration/test/service/OceanBaseService.java
Labels: branch-0.7

#5303 [5302]Improvement (trino-connector): Set the log level to debug for the logging of load catalog
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorManager.java
Labels: branch-0.7

#5310 [#5308] fix(docs): fix wrong key name of inUse parameter
  docs/manage-metalake-using-gravitino.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: branch-0.7

#5295 [#5150] fix (doc): Align the gravitino type in trino-connector doc
  docs/trino-connector/supported-catalog.md
Labels: branch-0.7

#5190 [#5180][part-1] improvement(test): Add more integration tests about access control
  authorizations/authorization-ranger/build.gradle.kts
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHivePlugin.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationPluginIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
  build.gradle.kts
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
Labels: branch-0.7

#5296 [#4582] fix(hadoop-catalog): Fix some location without slash issue
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
Labels: branch-0.7

#5307 [#5304] doc(core): add event listener document
  docs/gravitino-server-config.md
  docs/iceberg-rest-service.md
Labels: branch-0.7

#5273 [#4661] improve(build): Add LICENSE and NOTICE file to jar
  build.gradle.kts
Labels: branch-0.7

#5264 [#5262] feat(oceanbase-catalog): Add doc for OceanBase JDBC Catalog
  docs/jdbc-oceanbase-catalog.md
Labels: branch-0.7

#5272 [#5270] UI(oceanbase-catalog): Support OceanBase-CE JDBC catalog on the Web UI
  web/web/src/app/metalakes/metalake/MetalakeTree.js
  web/web/src/lib/icons/iconify-icons.css
  web/web/src/lib/icons/svg/oceanbase.svg
  web/web/src/lib/utils/initial.js
Labels: branch-0.7

#5320 [#5318][#5311][#5328] improvement(web): Add jdbc-driver properties for Paimon JDBC and fix jdbc issue
  web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/web/src/lib/utils/initial.js
Labels: branch-0.7

#4966 [#4994][#4369] feat(core): support S3 credential vending
  api/src/main/java/org/apache/gravitino/credential/GCSTokenCredential.java
  api/src/main/java/org/apache/gravitino/credential/S3SecretKeyCredential.java
  api/src/main/java/org/apache/gravitino/credential/S3TokenCredential.java
  bundles/aws-bundle/build.gradle.kts
  bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/credential/S3SecretKeyProvider.java
  bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/credential/S3TokenProvider.java
  bundles/aws-bundle/src/main/resources/META-INF/services/org.apache.gravitino.credential.CredentialProvider
  bundles/gcp-bundle/build.gradle.kts
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
  catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
  catalogs/catalog-common/src/main/java/org/apache/gravitino/storage/S3Properties.java
  common/src/main/java/org/apache/gravitino/credential/CredentialPropertyUtils.java
  common/src/test/java/org/apache/gravitino/credential/TestCredentialPropertiesUtils.java
  core/build.gradle.kts
  core/src/main/java/org/apache/gravitino/credential/config/S3CredentialConfig.java
  gradle/libs.versions.toml
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java
  iceberg/iceberg-rest-server/build.gradle.kts
  iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTS3IT.java
Labels: branch-0.7

#5345 [#5344] improvement(web): Show the type and storage location msg for fileset
  web/web/src/components/DetailsDrawer.js
Labels: branch-0.7

#5357 [#5353] doc(web): update web ui doc for 0.7.0
  docs/assets/webui/catalog-in-use.png
  docs/assets/webui/catalog-not-in-use.png
  docs/assets/webui/create-fileset.png
  docs/assets/webui/create-schema.png
  docs/assets/webui/created-catalog.png
  docs/assets/webui/delete-catalog.png
  docs/assets/webui/delete-fileset.png
  docs/assets/webui/delete-metalake.png
  docs/assets/webui/delete-schema.png
  docs/assets/webui/demo-columns.png
  docs/assets/webui/demo-tables.png
  docs/assets/webui/fileset-details.png
  docs/assets/webui/fileset-selected-details.png
  docs/assets/webui/list-columns.png
  docs/assets/webui/list-filesets.png
  docs/assets/webui/list-schemas.png
  docs/assets/webui/list-tables.png
  docs/assets/webui/metalake-details.png
  docs/assets/webui/metalake-in-use.png
  docs/assets/webui/metalake-list.png
  docs/assets/webui/metalake-not-in-use.png
  docs/assets/webui/props-authentication-kerberos.png
  docs/assets/webui/props-authentication-type.png
  docs/assets/webui/props-hudi.png
  docs/assets/webui/props-oceanbase.png
  docs/assets/webui/props-paimon-filesystem.png
  docs/assets/webui/props-paimon-hive.png
  docs/assets/webui/props-paimon-jdbc.png
  docs/assets/webui/schema-details.png
  docs/assets/webui/show-catalog-details.png
  docs/assets/webui/tree-view-reload-catalog.png
  docs/assets/webui/tree-view.png
  docs/assets/webui/update-catalog.png
  docs/assets/webui/update-fileset-dialog.png
  docs/assets/webui/update-schema-dialog.png
  docs/webui.md
Labels: branch-0.7

#5356 [MINOR] correct Iceberg multi catalog document
  docs/iceberg-rest-service.md
Labels: branch-0.7

#5335 [#4614] feat(auth-ranger): Support deny privilege in the RangerAuthorizationPlugin
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
Labels: branch-0.7

#5365 [#5364] feat(auth-ranger): Throw AuthorizationPluginException in authorization plugin
  api/src/main/java/org/apache/gravitino/exceptions/AuthorizationPluginException.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
  core/src/main/java/org/apache/gravitino/connector/authorization/RoleAuthorizationPlugin.java
  core/src/main/java/org/apache/gravitino/connector/authorization/UserGroupAuthorizationPlugin.java
Labels: branch-0.7

#5378 [#5359] fix(ob-catalog): fix ob catalog default value parse error
  catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/converter/OceanBaseColumnDefaultValueConverter.java
  catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/integration/test/CatalogOceanBaseIT.java
Labels: branch-0.7

#5387 [#5360] Improvement(web): hidden commont and property element for oceanbase schema
  web/web/src/app/metalakes/metalake/rightContent/CreateSchemaDialog.js
Labels: branch-0.7

#5376 [#5355] export Paimon jdbc user and password to properites
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java
Labels: branch-0.7

#5324 [#5081] improvement(docs): Add the document about cloud storage fileset.
  docs/hadoop-catalog.md
  docs/how-to-use-gvfs.md
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  docs/lakehouse-paimon-catalog.md
  docs/manage-fileset-metadata-using-gravitino.md
Labels: branch-0.7

#5358 [#5349] improvement(docker): Update Gravitino dockerfile to put cloud bundles into the docker image.
  dev/docker/gravitino/gravitino-dependency.sh
  docs/docker-image-details.md
Labels: branch-0.7

#5321 [#5146] fix(core): Support to rename and delete metadata object in the authorization plugin
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/FilesetHookDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/MetalakeHookDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/SchemaHookDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/TableHookDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/TopicHookDispatcher.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/test/java/org/apache/gravitino/catalog/TestFilesetOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestTopicOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/hook/TestFilesetHookDispatcher.java
  core/src/test/java/org/apache/gravitino/hook/TestTableHookDispatcher.java
  core/src/test/java/org/apache/gravitino/hook/TestTopicHookDispatcher.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
Labels: branch-0.7

#5368 [#5341] fix (trino-connector): Adjust the default precision of the time and timestamp types for different catalogs
  trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoQueryITBase.java
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/hive/00006_datatype.sql
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.sql
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.txt
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.sql
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.txt
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.sql
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.txt
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLDataTypeTransformer.java
Labels: branch-0.7
