Repository apache/gravitino, pull requests merged in 2024-06, with the labels that each got.

#3708 [MINOR] fix(pageIT): add Kafka catalog dependency to pageIT
  catalogs/catalog-kafka/build.gradle.kts
  integration-test/build.gradle.kts
Labels: branch-0.5

#3710 [MINOR] fix(pageIT): add Kafka catalog dependency to pageIT
  catalogs/catalog-kafka/build.gradle.kts
  integration-test/build.gradle.kts
Labels: cherry-pick

#3706 [HOTFIX][#3705] fix(spark-connector): write data to Iceberg table failed if drop and recreate Iceberg table
  docs/spark-connector/spark-catalog-iceberg.md
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
Labels: branch-0.5

#3714 [MINOR] test(spark-connector): remove metastored_db and derby.log after integration test
  .gitignore
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.5/spark/build.gradle.kts
Labels: branch-0.5

#3719 [MINOR] test(spark-connector): remove metastored_db and derby.log after integration test
  .gitignore
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.5/spark/build.gradle.kts
Labels: cherry-pick

#3718 [HOTFIX][#3705] fix(spark-connector): write data to Iceberg table failed if drop and recreate Iceberg table
  docs/spark-connector/spark-catalog-iceberg.md
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
  spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
Labels: cherry-pick

#3739 [MINOR] docs(spark-connector): correct Iceberg document
  docs/spark-connector/spark-catalog-iceberg.md
Labels: branch-0.5

#3740 [MINOR] docs(spark-connector): correct Iceberg document
  docs/spark-connector/spark-catalog-iceberg.md
Labels: cherry-pick

#3745 [MINOR] docs(spark-connector): polish iceberg doc
  docs/spark-connector/spark-catalog-iceberg.md
Labels: cherry-pick

#3753 [MINOR] docs: correct release version
  docs/docker-image-details.md
Labels: cherry-pick

#3761 [#3754] fix(doc): Fix configuration name error in documentation for the Trino connector installation
  docs/trino-connector/installation.md
Labels: branch-0.5

#3747 [#3746] improvement(spark-connector): Add scala version to maven artifact name for spark-connector
  spark-connector/v3.3/spark-runtime/build.gradle.kts
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.4/spark-runtime/build.gradle.kts
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.5/spark-runtime/build.gradle.kts
  spark-connector/v3.5/spark/build.gradle.kts
Labels: branch-0.5

#3763 [#3746] improvement(spark-connector): Add scala version to maven artifact name for spark-connector
  spark-connector/v3.3/spark-runtime/build.gradle.kts
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.4/spark-runtime/build.gradle.kts
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.5/spark-runtime/build.gradle.kts
  spark-connector/v3.5/spark/build.gradle.kts
Labels: cherry-pick

#3762 [#3754] fix(doc): Fix configuration name error in documentation for the Trino connector installation
  docs/trino-connector/installation.md
Labels: cherry-pick

#3748 [#3738] fix(docker): Fix query performance is lower than 0.5 version
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitSource.java
Labels: branch-0.5

#3781 [#3738] fix(trino-connector): Fix query performance is lower than 0.5 version
  trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitSource.java
Labels: cherry-pick

#3703 [#3403] fix(hive-catalog): add hive catalog property list-all-tables
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogPropertiesMeta.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java
  docs/apache-hive-catalog.md
Labels: branch-0.5

#3794 [#3403] fix(hive-catalog): add hive catalog property list-all-tables
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogPropertiesMeta.java
  catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java
  catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java
  docs/apache-hive-catalog.md
Labels: cherry-pick

#3806 [#3805] improvement(CI): upload logs of catalog and add free up disk space
  .github/workflows/build.yml
  .github/workflows/cron-integration-test.yml
  .github/workflows/python-integration-test.yml
Labels: branch-0.5

#3883 [#3881] fix(CI): move chmod to build stage to accelerate the startup speed for Doris
  catalogs/catalog-jdbc-doris/build.gradle.kts
  dev/docker/doris/Dockerfile
  dev/docker/doris/start.sh
  docs/docker-image-details.md
  integration-test/build.gradle.kts
Labels: upload log

#3873 [#3864] feat(lakehouse-iceberg): add custom catalog name to Iceberg catalog backend
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergConfig.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergCatalogUtil.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
  core/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
Labels: branch-0.5

#3957 [#3864] feat(lakehouse-iceberg): add custom catalog name to Iceberg catalog backend
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergConfig.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergCatalogUtil.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
  catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
  core/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
Labels: cherry-pick
