Repository apache/gravitino, pull requests merged in 2024-04, with the labels that each got.

#2763 [#2761] fix(docs): update docs after separating the Gravitino java client to two clients
  docs/manage-metalake-using-gravitino.md
  docs/manage-relational-metadata-using-gravitino.md
  docs/manage-table-partition-using-gravitino.md
  docs/security.md
Labels: documentation

#2833 [#2832] improvement(CI): Upload docker log
  .github/workflows/backend-integration-test.yml
  .github/workflows/frontend-integration-test.yml
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisAbstractIT.java
  docs/assets/upload-log-tag.png
  docs/how-to-test.md
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/BaseContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
Labels: upload log

#2843 [#2839] improvment(CI): add log of testcontainers
  .github/workflows/backend-integration-test.yml
  catalogs/catalog-hadoop/src/test/resources/log4j2.properties
  catalogs/catalog-hive/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties
  catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties
  catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java
  integration-test/src/test/resources/log4j2.properties
Labels: upload log

#2853 [MINOR] fix: update doris path in TestDorisAbstractIT
  catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisAbstractIT.java
Labels: upload log

#2847 [#2844] improve (test): Update the relations log file in the container in Docker Compose when CI fails.
  .github/workflows/backend-integration-test.yml
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoITContainers.java
  integration-test/trino-it/docker-compose.yaml
  integration-test/trino-it/inspect_ip.sh
  integration-test/trino-it/launch.sh
  integration-test/trino-it/shutdown.sh
Labels: upload log

#3106 [#2774] feat(doc): Add docs for messaging catalog
  docs/index.md
  docs/kafka-catalog.md
  docs/manage-messaging-metadata-using-gravitino.md
Labels: need backport, branch-0.5

#3112 [#2774] feat(doc): Add docs for messaging catalog
  docs/index.md
  docs/kafka-catalog.md
  docs/manage-messaging-metadata-using-gravitino.md
Labels: need backport, cherry-pick

#3107 [#3057] fix(web): fix breadcrumbs text display styles and appbar layout
  web/src/app/metalakes/metalake/MetalakeTree.js
  web/src/app/metalakes/metalake/rightContent/MetalakePath.js
  web/src/app/metalakes/metalake/rightContent/RightContent.js
  web/src/app/rootLayout/AppBar.js
  web/src/components/DetailsDrawer.js
Labels: need backport, branch-0.5

#3116 [#3062] fix(web): Support special character like "//" and improve the interceptors of axios
  web/src/lib/api/catalogs/index.js
  web/src/lib/api/filesets/index.js
  web/src/lib/api/schemas/index.js
  web/src/lib/api/tables/index.js
  web/src/lib/api/topics/index.js
  web/src/lib/provider/session.js
  web/src/lib/store/metalakes/index.js
  web/src/lib/utils/axios/index.ts
Labels: need backport, branch-0.5

#3110 [#3078] feat(core): Use \\w instead of [a-zA-Z0-9_] in regexp
  core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java
  core/src/test/java/com/datastrato/gravitino/connector/capability/TestCapability.java
Labels: need backport, branch-0.5

#3118 [#3062] fix(web): Support special character like "//" and improve the interceptors of axios
  web/src/lib/api/catalogs/index.js
  web/src/lib/api/filesets/index.js
  web/src/lib/api/schemas/index.js
  web/src/lib/api/tables/index.js
  web/src/lib/api/topics/index.js
  web/src/lib/provider/session.js
  web/src/lib/store/metalakes/index.js
  web/src/lib/utils/axios/index.ts
Labels: need backport, cherry-pick

#2907 [MINOR] improve(docs): update the doc of the web
  docs/assets/webui/create-fileset-hadoop-catalog-dialog.png
  docs/assets/webui/create-messaging-kafka-catalog-dialog.png
  docs/assets/webui/fileset-details.png
  docs/assets/webui/topic-details.png
  docs/webui.md
Labels: need backport, branch-0.5

#3115 [#2773] feat(doc): Add OAS for messaging catalog
  docs/open-api/filesets.yaml
  docs/open-api/openapi.yaml
  docs/open-api/topics.yaml
Labels: need backport, cherry-pick

#3117 [#3057] fix(web): fix breadcrumbs text display styles and appbar layout
  web/src/app/metalakes/metalake/MetalakeTree.js
  web/src/app/metalakes/metalake/rightContent/MetalakePath.js
  web/src/app/metalakes/metalake/rightContent/RightContent.js
  web/src/app/rootLayout/AppBar.js
  web/src/components/DetailsDrawer.js
Labels: need backport, cherry-pick

#2930 [#2929] improvement(pyClient): Optimize Python client code and add integration test
  clients/client-python/README.md
  clients/client-python/gravitino/api/catalog_change.py
  clients/client-python/gravitino/api/fileset.py
  clients/client-python/gravitino/api/fileset_change.py
  clients/client-python/gravitino/api/metalake.py
  clients/client-python/gravitino/api/metalake_change.py
  clients/client-python/gravitino/api/schema.py
  clients/client-python/gravitino/api/schema_change.py
  clients/client-python/gravitino/api/supports_schemas.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/client/gravitino_admin_client.py
  clients/client-python/gravitino/client/gravitino_client.py
  clients/client-python/gravitino/client/gravitino_client_base.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/dto_converters.py
  clients/client-python/gravitino/dto/fileset_dto.py
  clients/client-python/gravitino/dto/metalake_dto.py
  clients/client-python/gravitino/dto/requests/catalog_create_request.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/requests/catalog_updates_request.py
  clients/client-python/gravitino/dto/requests/fileset_create_request.py
  clients/client-python/gravitino/dto/requests/fileset_update_request.py
  clients/client-python/gravitino/dto/requests/fileset_updates_request.py
  clients/client-python/gravitino/dto/requests/metalake_create_request.py
  clients/client-python/gravitino/dto/requests/metalake_update_request.py
  clients/client-python/gravitino/dto/requests/metalake_updates_request.py
  clients/client-python/gravitino/dto/requests/schema_create_request.py
  clients/client-python/gravitino/dto/requests/schema_update_request.py
  clients/client-python/gravitino/dto/requests/schema_updates_request.py
  clients/client-python/gravitino/dto/responses/base_response.py
  clients/client-python/gravitino/dto/responses/catalog_list_response.py
  clients/client-python/gravitino/dto/responses/entity_list_response.py
  clients/client-python/gravitino/dto/responses/fileset_response.py
  clients/client-python/gravitino/dto/responses/metalake_list_response.py
  clients/client-python/gravitino/dto/responses/metalake_response.py
  clients/client-python/gravitino/dto/responses/schema_response.py
  clients/client-python/gravitino/dto/schema_dto.py
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/gravitino/namespace.py
  clients/client-python/tests/integration/integration_test_env.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_gravitino_admin_client.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
Labels: need backport, branch-0.5

#3124 [MINOR] improve(docs): update the doc of the web
  docs/assets/webui/create-fileset-hadoop-catalog-dialog.png
  docs/assets/webui/create-messaging-kafka-catalog-dialog.png
  docs/assets/webui/fileset-details.png
  docs/assets/webui/topic-details.png
  docs/webui.md
Labels: need backport, cherry-pick

#3125 [#2929] improvement(pyClient): Optimize Python client code and add integration test
  clients/client-python/README.md
  clients/client-python/gravitino/api/catalog_change.py
  clients/client-python/gravitino/api/fileset.py
  clients/client-python/gravitino/api/fileset_change.py
  clients/client-python/gravitino/api/metalake.py
  clients/client-python/gravitino/api/metalake_change.py
  clients/client-python/gravitino/api/schema.py
  clients/client-python/gravitino/api/schema_change.py
  clients/client-python/gravitino/api/supports_schemas.py
  clients/client-python/gravitino/catalog/base_schema_catalog.py
  clients/client-python/gravitino/catalog/fileset_catalog.py
  clients/client-python/gravitino/client/gravitino_admin_client.py
  clients/client-python/gravitino/client/gravitino_client.py
  clients/client-python/gravitino/client/gravitino_client_base.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/dto/dto_converters.py
  clients/client-python/gravitino/dto/fileset_dto.py
  clients/client-python/gravitino/dto/metalake_dto.py
  clients/client-python/gravitino/dto/requests/catalog_create_request.py
  clients/client-python/gravitino/dto/requests/catalog_update_request.py
  clients/client-python/gravitino/dto/requests/catalog_updates_request.py
  clients/client-python/gravitino/dto/requests/fileset_create_request.py
  clients/client-python/gravitino/dto/requests/fileset_update_request.py
  clients/client-python/gravitino/dto/requests/fileset_updates_request.py
  clients/client-python/gravitino/dto/requests/metalake_create_request.py
  clients/client-python/gravitino/dto/requests/metalake_update_request.py
  clients/client-python/gravitino/dto/requests/metalake_updates_request.py
  clients/client-python/gravitino/dto/requests/schema_create_request.py
  clients/client-python/gravitino/dto/requests/schema_update_request.py
  clients/client-python/gravitino/dto/requests/schema_updates_request.py
  clients/client-python/gravitino/dto/responses/base_response.py
  clients/client-python/gravitino/dto/responses/catalog_list_response.py
  clients/client-python/gravitino/dto/responses/entity_list_response.py
  clients/client-python/gravitino/dto/responses/fileset_response.py
  clients/client-python/gravitino/dto/responses/metalake_list_response.py
  clients/client-python/gravitino/dto/responses/metalake_response.py
  clients/client-python/gravitino/dto/responses/schema_response.py
  clients/client-python/gravitino/dto/schema_dto.py
  clients/client-python/gravitino/name_identifier.py
  clients/client-python/gravitino/namespace.py
  clients/client-python/tests/integration/integration_test_env.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/integration/test_gravitino_admin_client.py
  clients/client-python/tests/integration/test_metalake.py
  clients/client-python/tests/integration/test_schema.py
Labels: need backport, cherry-pick

#3119 [#3078] feat(core): Use \\w instead of [a-zA-Z0-9_] in regexp
  core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java
  core/src/test/java/com/datastrato/gravitino/connector/capability/TestCapability.java
Labels: need backport, cherry-pick

#3122 [#3101] fix(all): Only validate the name when creating
  api/src/main/java/com/datastrato/gravitino/exceptions/GravitinoRuntimeException.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java
  core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java
  core/src/main/java/com/datastrato/gravitino/catalog/FilesetNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/SchemaNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/TableNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/TopicNormalizeDispatcher.java
Labels: need backport, branch-0.5

#3126 [#3101] fix(all): Only validate the name when creating
  api/src/main/java/com/datastrato/gravitino/exceptions/GravitinoRuntimeException.java
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java
  core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java
  core/src/main/java/com/datastrato/gravitino/catalog/FilesetNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/SchemaNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/TableNormalizeDispatcher.java
  core/src/main/java/com/datastrato/gravitino/catalog/TopicNormalizeDispatcher.java
Labels: need backport, cherry-pick

#3065 [#2852] feat(core): Add relational backend for Role Entity
  core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/po/RolePO.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
  core/src/test/java/com/datastrato/gravitino/storage/memory/TestMemoryEntityStore.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/resources/h2/schema-h2.sql
  scripts/mysql/schema-0.5.0-mysql.sql
Labels: need backport, branch-0.5

#3135 [#2852] feat(core): Add relational backend for Role Entity
  core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserRoleRelMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/po/RolePO.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
  core/src/test/java/com/datastrato/gravitino/storage/memory/TestMemoryEntityStore.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/resources/h2/schema-h2.sql
  scripts/mysql/schema-0.5.0-mysql.sql
Labels: need backport, cherry-pick

#3134 [#2115] fix(jdbc-catalog): Can't create a table in database with the same name prefix.
  catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Labels: need backport, cherry-pick

#3141 [#3140] docs(partition): add docs and OAS for drop partition operation
  docs/manage-table-partition-using-gravitino.md
  docs/open-api/partitions.yaml
  docs/open-api/tables.yaml
Labels: need backport, branch-0.5

#3142 [#3139] fix(core): Fix NPE issue during creating catalog when properties are not specified
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
Labels: need backport, branch-0.5

#3145 [#3140] docs(partition): add docs and OAS for drop partition operation
  docs/manage-table-partition-using-gravitino.md
  docs/open-api/partitions.yaml
  docs/open-api/tables.yaml
Labels: need backport, cherry-pick

#3146 [#3139] fix(core): Fix NPE issue during creating catalog when properties are not specified
  core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
Labels: need backport, cherry-pick

#3156 [#3154] improvement(docs): Add the change log for 0.5.0 version image
  docs/docker-image-details.md
Labels: need backport, branch-0.5

#3157 [#3154] improvement(docs): Add the change log for 0.5.0 version image
  docs/docker-image-details.md
Labels: need backport, cherry-pick

#3159 [Minor] fix(docs): Change Java doc link to 0.5.0
  docs/index.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: need backport, branch-0.5

#3160 [Minor] fix(docs): Change Java doc link to 0.5.0
  docs/index.md
  docs/manage-relational-metadata-using-gravitino.md
Labels: need backport, cherry-pick

#3162 [#3158] fix(doc): correct iceberg rest catalog service verify url
  docs/iceberg-rest-service.md
Labels: need backport, branch-0.5

#3168 [#3158] fix(doc): correct iceberg rest catalog service verify url
  docs/iceberg-rest-service.md
Labels: need backport, cherry-pick

#3143 [#3132] improvement(core): Use a more elegant validation of User, Group and Role NameIdentifier
  core/src/main/java/com/datastrato/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAuthorizationUtils.java
Labels: need backport, branch-0.5

#3170 [#3132] improvement(core): Use a more elegant validation of User, Group and Role NameIdentifier
  core/src/main/java/com/datastrato/gravitino/authorization/AuthorizationUtils.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAuthorizationUtils.java
Labels: need backport, cherry-pick

#3166 [#3081] improvement(core): Remove hack in BaseCatalog.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
Labels: need backport, branch-0.5

#3164 [#3163] Refactor(spark-connector): Refactor Spark-connector IT to support more iceberg catalog backends
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogHiveBackendIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
Labels: need backport, branch-0.5

#3178 [#3163] Refactor(spark-connector): Refactor Spark-connector IT to support more iceberg catalog backends
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogHiveBackendIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
Labels: need backport, cherry-pick

#3169 [#3129] fix(spark-connector): fix create table failed for using hive
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java
  spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java
  spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
Labels: need backport, branch-0.5

#3172 [#3081] improvement(core): Remove hack in BaseCatalog.java
  core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
Labels: need backport, cherry-pick

#3176 [#3161] fix(jdbc-pg): Fix getting PostgreSQL jdbc driver error
  catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSQLCatalogOperations.java
  catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Labels: need backport, cherry-pick

#3201 [#3207] fix(test): Trigger integration test with changes in module `integration-test-common`
  .github/workflows/backend-integration-test.yml
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/MiniGravitino.java
Labels: need backport, branch-0.5

#3208 [#3207] fix(test): Trigger integration test with changes in module `integration-test-common`
  .github/workflows/backend-integration-test.yml
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/MiniGravitino.java
Labels: need backport, cherry-pick

#3219 [#3218]fix(doc): Fix the wrong sequence number issue in doc and improve the wording
  docs/how-to-build.md
Labels: need backport, branch-0.5

#3220 [#3218]fix(doc): Fix the wrong sequence number issue in doc and improve the wording
  docs/how-to-build.md
Labels: need backport, cherry-pick

#3197 [#3024] improvement(IT): close containers and upload container log after all tests are finished
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/KafkaContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
Labels: need backport, upload log, branch-0.5

#3224 [MINOR] docs(lakehouse-iceberg): polish iceberg rest catalog document
  docs/iceberg-rest-service.md
Labels: need backport, branch-0.5

#3191 [#3190] fix(jdbc-backend): Fix the cast issue when Relational Garbage Collector cleaning fileset version info
  core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalGarbageCollector.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/FilesetVersionMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/po/FilesetMaxVersionPO.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/store/relational/service/FilesetMetaServiceIT.java
Labels: need backport, branch-0.5

#3223 [#3024] improvement(IT): close containers and upload container log after all tests are finished
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/KafkaContainer.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java
  integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
Labels: need backport, cherry-pick, upload log

#3225 [MINOR] docs(lakehouse-iceberg): polish iceberg rest catalog document
  docs/iceberg-rest-service.md
Labels: need backport, cherry-pick

#3217 [#3216] fix(core): Fix the issue of method `checkValue` in the ConfigOption
  common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java
  common/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java
  core/src/main/java/com/datastrato/gravitino/Configs.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java
Labels: need backport, branch-0.5

#3226 [#3190] fix(jdbc-backend): Fix the cast issue when Relational Garbage Collector cleaning fileset version info
  core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalGarbageCollector.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/FilesetVersionMapper.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/po/FilesetMaxVersionPO.java
  core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java
  integration-test/build.gradle.kts
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/store/relational/service/FilesetMetaServiceIT.java
Labels: need backport, cherry-pick

#3231 [#3216] fix(core): Fix the issue of method `checkValue` in the ConfigOption
  common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java
  common/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java
  core/src/main/java/com/datastrato/gravitino/Configs.java
  core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java
Labels: need backport, cherry-pick

#3235 [#3234] improve (doc): Update playground docs for using simple catalog
  docs/how-to-use-the-playground.md
Labels: need backport, branch-0.5

#3236 [#3234] improve (doc): Update playground docs for using simple catalog
  docs/how-to-use-the-playground.md
Labels: need backport, cherry-pick

#3179 [#3165] fix(client-java): Fix the http client `toJson` encode without UTF-8
  catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
  integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/MetalakeIT.java
Labels: need backport, branch-0.5
