Repository apache/gravitino, pull requests merged in 2024-09, with the labels that each got.

#4597 [#4367] feat(iceberg): add OSS support for Gravitino Iceberg REST server
  LICENSE.bin
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
  docs/iceberg-rest-service.md
  docs/lakehouse-iceberg-catalog.md
  docs/spark-connector/spark-catalog-iceberg.md
  gradle/libs.versions.toml
  iceberg/iceberg-common/build.gradle.kts
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergTableOps.java
Labels: ICEBERG-REST-SERVER

#4847 [MINOR] fix broken link
  docs/how-to-build.md
Labels: branch-0.6

#4846 [#4845] fix(core): Fix bugs when updating metalake or catalog with nullable comment.
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaMapper.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/client/CatalogIT.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/client/MetalakeIT.java
Labels: branch-0.6

#4854 [#4851] fix: make `TestHiveTableOperations` setup independently
  catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTable.java
  catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTableOperations.java
Labels: branch-0.6

#4808 [#4758] correct Iceberg document location is immutable not reserved
  docs/lakehouse-iceberg-catalog.md
Labels: branch-0.6

#4690 [#4608] feat(core): Supports to load fields lazily
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
  core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java
  core/src/main/java/org/apache/gravitino/meta/GroupEntity.java
  core/src/main/java/org/apache/gravitino/meta/RoleEntity.java
  core/src/main/java/org/apache/gravitino/meta/UserEntity.java
  core/src/main/java/org/apache/gravitino/proto/GroupEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/ProtoEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/RoleEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/UserEntitySerDe.java
  core/src/main/java/org/apache/gravitino/storage/kv/BinaryEntityKeyEncoder.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/SupplierUtils.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java
  core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java
  core/src/test/java/org/apache/gravitino/meta/TestEntity.java
  core/src/test/java/org/apache/gravitino/proto/TestEntityProtoSerDe.java
  core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
  core/src/test/java/org/apache/gravitino/storage/memory/TestMemoryEntityStore.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestGroupMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestGroupOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestPermissionOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Labels: branch-0.6

#4876 [HOTFIX] fix(openapi): fix the env of openAPI lint plugin
  .github/workflows/build.yml
  docs/build.gradle.kts
Labels: branch-0.6

#4872 (#4871)fix(test): Fix the jvm args `-Xmx4G` of gradle test can be overwrite by the `extraJvmArgs`.
  build.gradle.kts
Labels: branch-0.6

#4899 [MINOR] docs: polish document for spark connector and Iceberg REST server
  docs/iceberg-rest-service.md
  docs/manage-relational-metadata-using-gravitino.md
  docs/spark-connector/spark-connector.md
Labels: branch-0.6

#4908 [MINOR] docs: fix md links issue
  docs/getting-started.md
  docs/how-to-build.md
  docs/index.md
Labels: branch-0.6

#4915 [#4914] fix(web): fix testCheckLinkDocs test case issue
  web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java
Labels: branch-0.6

#4917 [#4742] Improvement(ui): support creating paimon catalog
  web/web/src/app/metalakes/metalake/MetalakeTree.js
  web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
  web/web/src/lib/icons/iconify-icons.css
  web/web/src/lib/icons/svg/paimon.svg
  web/web/src/lib/utils/initial.js
Labels: branch-0.6

#4893 [#4743]fix(trino-connector): Fix the default precision of time and timestamp in the Iceberg catalog.
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.sql
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.txt
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/util/GeneralDataTypeTransformer.java
  trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/iceberg/TestIcebergDataTypeTransformer.java
  trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/util/TestDataTypeTransformer.java
Labels: branch-0.6

#4945 Revert "[#4608] feat(core): Supports to load fields lazily"
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
  core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
  core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java
  core/src/main/java/org/apache/gravitino/meta/GroupEntity.java
  core/src/main/java/org/apache/gravitino/meta/RoleEntity.java
  core/src/main/java/org/apache/gravitino/meta/UserEntity.java
  core/src/main/java/org/apache/gravitino/proto/GroupEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/ProtoEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/RoleEntitySerDe.java
  core/src/main/java/org/apache/gravitino/proto/UserEntitySerDe.java
  core/src/main/java/org/apache/gravitino/storage/kv/BinaryEntityKeyEncoder.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/SupplierUtils.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java
  core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java
  core/src/test/java/org/apache/gravitino/meta/TestEntity.java
  core/src/test/java/org/apache/gravitino/proto/TestEntityProtoSerDe.java
  core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
  core/src/test/java/org/apache/gravitino/storage/memory/TestMemoryEntityStore.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestGroupMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestGroupOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestPermissionOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Labels: branch-0.6

#4969 [Minor] docs: Fix doc misspelling
  docs/trino-connector/installation.md
Labels: branch-0.6

#4900 [#4718] fix(iceberg): use unified logic to transform catalog backend name to handle the renaming of catalog
  catalogs/catalog-common/build.gradle.kts
  catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
  catalogs/catalog-common/src/test/java/org/apache/gravitino/lakehouse/iceberg/TestIcebergPropertiesUtils.java
  catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
  docs/lakehouse-iceberg-catalog.md
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergConnectorAdapter.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/metadata/GravitinoCatalog.java
Labels: branch-0.6

#4055 [#3348] feat(core,server): Add the list operation of the user
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestUserGroup.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
  common/src/main/java/org/apache/gravitino/dto/responses/UserListResponse.java
  common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
  core/src/main/java/org/apache/gravitino/EntityStore.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
  core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java
  core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
  core/src/main/java/org/apache/gravitino/meta/UserEntity.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/h2/UserMetaH2Provider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/postgresql/UserMetaPostgreSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/po/ExtendedUserPO.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFields.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFieldsHandlers.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
  server/src/main/java/org/apache/gravitino/server/web/rest/UserOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Labels: branch-0.6

#5004 [#3348] feat(core,server): Add the list operation of the user
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestUserGroup.java
  common/src/main/java/org/apache/gravitino/dto/responses/UserListResponse.java
  common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
  core/src/main/java/org/apache/gravitino/EntityStore.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
  core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java
  core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
  core/src/main/java/org/apache/gravitino/meta/UserEntity.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/h2/UserMetaH2Provider.java
  core/src/main/java/org/apache/gravitino/storage/relational/po/ExtendedUserPO.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFields.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFieldsHandlers.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
  integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlIT.java
  server/src/main/java/org/apache/gravitino/server/web/rest/UserOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Labels: cherry-pick

#5003 [MINOR] docs(core): fix iceberg event listener configuration
  docs/gravitino-server-config.md
Labels: branch-0.6

#5016 Fix API description issue
  docs/manage-metalake-using-gravitino.md
Labels: branch-0.6

#4894 [#3346] feat(core,server): Supports to list roles operations
  api/src/main/java/org/apache/gravitino/authorization/Role.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestRole.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
  common/src/main/java/org/apache/gravitino/dto/authorization/RoleDTO.java
  common/src/main/java/org/apache/gravitino/dto/responses/RoleResponse.java
  core/src/main/java/org/apache/gravitino/EntityStore.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
  core/src/main/java/org/apache/gravitino/authorization/RoleManager.java
  core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java
  core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
  core/src/main/java/org/apache/gravitino/meta/RoleEntity.java
  core/src/main/java/org/apache/gravitino/meta/UserEntity.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/RoleMetaBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFields.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFieldsHandlers.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/org/apache/gravitino/meta/TestEntity.java
  core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Labels: branch-0.6

#5011 [#5010] Add LICENSE and NOTICE files for Iceberg REST binary
  LICENSE.rest
  NOTICE.rest
  build.gradle.kts
Labels: branch-0.6

#5027 [#5000] improvement(server): Move tag object API to object path
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java
  docs/manage-tags-in-gravitino.md
  docs/open-api/openapi.yaml
  docs/open-api/tags.yaml
  server/src/main/java/org/apache/gravitino/server/web/rest/MetadataObjectTagOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/TagOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestMetadataObjectTagOperations.java
Labels: branch-0.6

#5023 [#4886] feat(server,core): Supports to list roles by object
  api/src/main/java/org/apache/gravitino/Catalog.java
  api/src/main/java/org/apache/gravitino/Metalake.java
  api/src/main/java/org/apache/gravitino/Schema.java
  api/src/main/java/org/apache/gravitino/authorization/SupportsRoles.java
  api/src/main/java/org/apache/gravitino/file/Fileset.java
  api/src/main/java/org/apache/gravitino/messaging/Topic.java
  api/src/main/java/org/apache/gravitino/rel/Table.java
  clients/client-java/src/main/java/org/apache/gravitino/client/BaseSchemaCatalog.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericSchema.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericTopic.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectRoleOperations.java
  clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportRoles.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
  core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
  core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
  core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java
  core/src/main/java/org/apache/gravitino/authorization/RoleManager.java
  core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
  core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
  server/src/main/java/org/apache/gravitino/server/web/rest/MetadataObjectRoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestMetadataObjectRoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Labels: branch-0.6

#4975 fix(authorization-ranger):the descr field of ranger table x_group is not null
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/reference/VXGroup.java
Labels: branch-0.6

#5037 [MINOR] improve(CI): Increase the Python timeout minutes to 45 minutes
  .github/workflows/python-integration-test.yml
Labels: branch-0.6

#5039 [#4956] fix(docs): Correct array and union and struct mapping document for Gravitino
  docs/apache-hive-catalog.md
  docs/lakehouse-iceberg-catalog.md
  docs/lakehouse-paimon-catalog.md
Labels: branch-0.6

#5035 [#5033] improvement(docs): Add the documents about access control
  docs/open-api/groups.yaml
  docs/open-api/openapi.yaml
  docs/open-api/permissions.yaml
  docs/open-api/roles.yaml
  docs/open-api/tags.yaml
  docs/open-api/users.yaml
  docs/security/access-control.md
Labels: branch-0.6

#4991 [#4988] fix(doris-catalog): Fix the missing distribution information when loading Doris tables
  api/src/main/java/org/apache/gravitino/rel/expressions/distributions/Strategy.java
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogOperations.java
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcTable.java
  catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/utils/DorisUtils.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTableOperations.java
  common/src/main/java/org/apache/gravitino/dto/rel/PartitionUtils.java
  docs/jdbc-doris-catalog.md
  docs/manage-relational-metadata-using-gravitino.md
  docs/table-partitioning-distribution-sort-order-indexes.md
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00000_create_table.txt
Labels: branch-0.6

#5043 [#5042] fix(ui): show the expend arrow when reload tree node
  web/web/src/app/metalakes/metalake/MetalakeTree.js
  web/web/src/lib/store/metalakes/index.js
  web/web/src/lib/utils/index.js
Labels: branch-0.6

#5053 [#5054] improvement(api,server): Add the check of privileges
  api/src/main/java/org/apache/gravitino/authorization/Privilege.java
  api/src/main/java/org/apache/gravitino/authorization/Privileges.java
  api/src/test/java/org/apache/gravitino/authorization/TestSecurableObjects.java
  common/src/main/java/org/apache/gravitino/dto/authorization/PrivilegeDTO.java
  common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
  core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
  server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Labels: branch-0.6
