Repository apache/gravitino, pull requests merged in 2025-04, with the labels that each got.

#6818 [MINOR] fix(CI): update dorny/paths-filter@v3 to dorny/paths-filter@v3.0.2
  .github/workflows/access-control-integration-test.yml
  .github/workflows/backend-integration-test.yml
  .github/workflows/build.yml
  .github/workflows/cron-integration-test.yml
  .github/workflows/flink-integration-test.yml
  .github/workflows/frontend-integration-test.yml
  .github/workflows/gvfs-fuse-build-test.yml
  .github/workflows/python-integration-test.yml
  .github/workflows/spark-integration-test.yml
  .github/workflows/trino-integration-test.yml
Labels: branch-0.8

#6843 [#6834] fix(release-build): wrong path of license + notice bin files
  dev/release/release-build.sh
Labels: branch-0.8

#6778 [#6777] fix(server,authn): Fix use catalog and show databases failed with krb cluster issue
  catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveProxyPlugin.java
Labels: branch-0.8

#6885 [MINOR] docs: fix several typo in docs
  .gitignore
  docs/how-to-upgrade.md
  docs/how-to-use-gvfs.md
  docs/jdbc-mysql-catalog.md
  docs/lakehouse-paimon-catalog.md
  docs/manage-fileset-metadata-using-gravitino.md
  docs/metrics.md
Labels: branch-0.8

#6884 [#6722] fix(jdbc-doris): use `show backends` to get the count of Doris BE nodes
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
Labels: 0.9.0

#6878 [#6874] improvement(core): Set `testOnBorrow` to true to avoid possible connection timeout problem
  core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
Labels: branch-0.9

#6897 [#6889] feat(fileset): add multiple locations APIs for fileset
  api/src/main/java/org/apache/gravitino/exceptions/NoSuchLocationNameException.java
  api/src/main/java/org/apache/gravitino/file/Fileset.java
  api/src/main/java/org/apache/gravitino/file/FilesetCatalog.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogPropertiesMetadata.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopSchemaPropertiesMetadata.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  clients/client-python/gravitino/api/file/fileset.py
  clients/client-python/gravitino/client/fileset_catalog.py
  clients/client-python/gravitino/client/generic_fileset.py
  clients/client-python/gravitino/dto/fileset_dto.py
  clients/client-python/gravitino/exceptions/base.py
Labels: branch-0.9

#6922 [#6892] feat(core): support fileset multiple locations in core module
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFileset.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
  clients/client-python/tests/integration/test_fileset_catalog.py
  core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java
  core/src/main/java/org/apache/gravitino/catalog/FilesetNormalizeDispatcher.java
  core/src/main/java/org/apache/gravitino/catalog/FilesetOperationDispatcher.java
  core/src/main/java/org/apache/gravitino/connector/BaseFileset.java
  core/src/main/java/org/apache/gravitino/hook/FilesetHookDispatcher.java
  core/src/main/java/org/apache/gravitino/listener/FilesetEventDispatcher.java
  core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationFailureEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationPreEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/info/FilesetInfo.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java
  core/src/test/java/org/apache/gravitino/TestFileset.java
  core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
  core/src/test/java/org/apache/gravitino/listener/api/event/TestFilesetEvent.java
  core/src/test/java/org/apache/gravitino/meta/TestEntityCombinedObject.java
Labels: branch-0.9

#6873 [#6871] fix(server,authn): Fix use catalog and show databases failed with krb cluster for iceberg issue
  iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/authentication/kerberos/HiveBackendProxy.java
Labels: branch-0.9

#6891 [#6781] feat(lineage): support lineage sinks
  core/src/main/java/org/apache/gravitino/listener/AsyncQueueListener.java
  core/src/main/java/org/apache/gravitino/listener/EventBus.java
  core/src/main/java/org/apache/gravitino/listener/EventListenerManager.java
  core/src/main/java/org/apache/gravitino/listener/EventListenerPluginWrapper.java
  core/src/main/java/org/apache/gravitino/listener/api/event/EventWrapper.java
  lineage/build.gradle.kts
  lineage/src/main/java/org/apache/gravitino/lineage/LineageConfig.java
  lineage/src/main/java/org/apache/gravitino/lineage/LineageService.java
  lineage/src/main/java/org/apache/gravitino/lineage/sink/LineageLogSink.java
  lineage/src/main/java/org/apache/gravitino/lineage/sink/LineageSinkEventListener.java
  lineage/src/main/java/org/apache/gravitino/lineage/sink/LineageSinkManager.java
  lineage/src/test/java/org/apache/gravitino/lineage/TestLineageConfig.java
  lineage/src/test/java/org/apache/gravitino/lineage/sink/LineageSinkForTest.java
  lineage/src/test/java/org/apache/gravitino/lineage/sink/TestLineageSinkManager.java
  server-common/build.gradle.kts
  server-common/src/main/java/org/apache/gravitino/server/web/ObjectMapperProvider.java
Labels: branch-0.9

#6924 [#6893] feat(server): support fileset multiple locations in REST API
  clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportCredentials.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportRoles.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
  common/src/main/java/org/apache/gravitino/dto/file/FilesetDTO.java
  common/src/main/java/org/apache/gravitino/dto/requests/FilesetCreateRequest.java
  common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
  common/src/test/java/org/apache/gravitino/dto/file/TestFilesetDTO.java
  docs/open-api/filesets.yaml
  server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
Labels: branch-0.9

#6935 [#6894] feat(client): Java/Python clients supports fileset multiple locations
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
  clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
  clients/client-python/gravitino/client/fileset_catalog.py
  clients/client-python/gravitino/client/generic_fileset.py
  clients/client-python/gravitino/dto/fileset_dto.py
  clients/client-python/gravitino/dto/requests/fileset_create_request.py
  clients/client-python/gravitino/dto/responses/fileset_response.py
  clients/client-python/gravitino/exceptions/handlers/fileset_error_handler.py
  clients/client-python/tests/integration/test_fileset_catalog.py
  clients/client-python/tests/unittests/mock_base.py
  common/src/main/java/org/apache/gravitino/dto/responses/FilesetResponse.java
Labels: branch-0.9

#6937 [#6895] feat(GVFS): support specifying the location name in GVFS
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java
  clients/client-python/gravitino/filesystem/gvfs.py
  clients/client-python/gravitino/filesystem/gvfs_config.py
  clients/client-python/tests/integration/test_gvfs_with_hdfs.py
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemIT.java
  docs/how-to-use-gvfs.md
Labels: branch-0.9

#6861 [#6815] feat(core): Support update comment for model version
  api/src/main/java/org/apache/gravitino/model/ModelCatalog.java
  api/src/main/java/org/apache/gravitino/model/ModelChange.java
  api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
  api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java
  catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
  catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelCatalog.java
  core/src/main/java/org/apache/gravitino/catalog/ModelNormalizeDispatcher.java
  core/src/main/java/org/apache/gravitino/catalog/ModelOperationDispatcher.java
  core/src/main/java/org/apache/gravitino/hook/ModelHookDispatcher.java
  core/src/main/java/org/apache/gravitino/listener/ModelEventDispatcher.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionFailureEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionPreEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/OperationType.java
  core/src/main/java/org/apache/gravitino/listener/api/info/Either.java
  core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/ModelVersionMetaMapper.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/ModelVersionMetaSQLProviderFactory.java
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/ModelVersionMetaBaseSQLProvider.java
  core/src/main/java/org/apache/gravitino/storage/relational/service/ModelVersionMetaService.java
  core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
  core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
  core/src/test/java/org/apache/gravitino/listener/api/event/TestEither.java
  core/src/test/java/org/apache/gravitino/listener/api/event/TestModelEvent.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelVersionMetaService.java
  docs/gravitino-server-config.md
Labels: branch-0.9

#6955 [Minor] Fix web license and notice files in the binary release
  build.gradle.kts
Labels: branch-0.8, branch-0.9

#6952 [#6604] Improvement(GVFS): extract methods from gvfs to utils for reusing
  clients/client-python/gravitino/filesystem/gvfs.py
  clients/client-python/gravitino/filesystem/gvfs_utils.py
  clients/client-python/tests/unittests/test_gvfs_with_local.py
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemUtils.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
Labels: branch-0.9

#6954 [#6953] feat(GVFS): Refactor GVFS to handle fileset not existed scenario
  clients/client-python/gravitino/filesystem/gvfs.py
  clients/client-python/tests/unittests/test_gvfs_without_fileset.py
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/FilesetPathNotFoundException.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
Labels: branch-0.9

#6599 [#6594] feat(deploy): Provide gravitino chart for deploying different storage backend on K8S
  .github/workflows/chart-test.yaml
  LICENSE
  dev/charts/gravitino/.helmignore
  dev/charts/gravitino/Chart.yaml
  dev/charts/gravitino/resources/config/gravitino.conf
  dev/charts/gravitino/resources/config/init.sh
  dev/charts/gravitino/resources/config/log4j2.properties
  dev/charts/gravitino/resources/files/mysql
  dev/charts/gravitino/resources/scenarios/ci-values.yaml
  dev/charts/gravitino/templates/NOTES.txt
  dev/charts/gravitino/templates/_helpers.tpl
  dev/charts/gravitino/templates/configmap-mysql-init.yaml
  dev/charts/gravitino/templates/configmap.yaml
  dev/charts/gravitino/templates/deployment.yaml
  dev/charts/gravitino/templates/ingress.yaml
  dev/charts/gravitino/templates/service.yaml
  dev/charts/gravitino/templates/tests/test-connection.yaml
  dev/charts/gravitino/values.yaml
  dev/ci/chart_schema.yaml
  dev/ci/lintconf.yaml
  docs/chart.md
Labels: branch-0.9

#6951 [#5362] fix(client-python): fix wrong Gravitino version
  clients/client-python/gravitino/client/gravitino_version.py
  clients/client-python/tests/unittests/test_gravitino_version.py
Labels: branch-0.9

#6961 [#6939] feat(GVFS): make Java GVFS operations customizable
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/BaseGVFSOperations.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/DefaultGVFSOperations.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/FilesetCatalogCache.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/FilesetPathNotFoundException.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
  docs/how-to-use-gvfs.md
Labels: branch-0.9

#6975 [MINOR] Revert changes that remove getter method in EntityCombinedFileset
  core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java
  core/src/test/java/org/apache/gravitino/catalog/TestEntityCombinedFileset.java
Labels: branch-0.9

#6964 [#6956] feat(GVFS): make Python GVFS operations customizable
  clients/client-python/gravitino/filesystem/gvfs.py
  clients/client-python/gravitino/filesystem/gvfs_base_operations.py
  clients/client-python/gravitino/filesystem/gvfs_config.py
  clients/client-python/gravitino/filesystem/gvfs_default_operations.py
  clients/client-python/gravitino/filesystem/gvfs_storage_handler.py
  clients/client-python/tests/integration/test_gvfs_with_hdfs.py
  clients/client-python/tests/unittests/mock_base.py
  clients/client-python/tests/unittests/test_gvfs_with_local.py
  clients/client-python/tests/unittests/test_gvfs_without_fileset.py
  docs/how-to-use-gvfs.md
Labels: branch-0.9

#6967 [#6815] feat(server): Support update comment for model version
  api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
  catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
  catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
  clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
  clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
  clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
  clients/cli/src/main/java/org/apache/gravitino/cli/SimpleCommandHandler.java
  clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
  clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionComment.java
  clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
  clients/cli/src/test/java/org/apache/gravitino/cli/TestSimpleCommands.java
  clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelCatalog.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericModelCatalog.java
  clients/client-python/gravitino/api/model_version_change.py
  clients/client-python/gravitino/client/generic_model_catalog.py
  clients/client-python/gravitino/dto/requests/model_version_update_request.py
  clients/client-python/gravitino/dto/requests/model_version_updates_request.py
  clients/client-python/tests/integration/test_model_catalog.py
  clients/client-python/tests/unittests/test_model_catalog_api.py
  common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java
  common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdatesRequest.java
  core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
  server/src/main/java/org/apache/gravitino/server/web/rest/ModelOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestModelOperations.java
Labels: branch-0.9

#6979 [#6081] docs: add required tag to type in set owner's request body
  docs/open-api/owners.yaml
Labels: branch-0.9

#6973 [#6940] feat(fileset): support disable Hadoop catalog auto creation of directories
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogPropertiesMetadata.java
  catalogs/catalog-hadoop/src/main/resources/hadoop.conf
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemIT.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFilesystemWithFSOpsDisabledIT.java
  docs/hadoop-catalog.md
Labels: branch-0.9

#6992 [#6991] fix(gvfs): Exclude log4j in gvfs runtime jar
  api/build.gradle.kts
  clients/client-java/build.gradle.kts
  clients/filesystem-hadoop3-runtime/build.gradle.kts
  clients/filesystem-hadoop3/build.gradle.kts
Labels: branch-0.9

#6988 [#2904] feat(fileset): add cache for fileset
  catalogs/catalog-hadoop/build.gradle.kts
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogPropertiesMetadata.java
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  docs/hadoop-catalog.md
Labels: branch-0.9

#7006 [#6940] fix(gvfs): fix python gvfs missing auto-create fileset dir
  clients/client-python/gravitino/filesystem/gvfs_base_operations.py
Labels: branch-0.9

#6999 [#6875] fix: Update outdated comments for complex types
  api/src/main/java/org/apache/gravitino/rel/types/Types.java
  clients/client-python/gravitino/api/types/types.py
Labels: branch-0.9

#7010 [#6813] feat(server): Support update URI for model version
  api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
  api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java
  catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
  catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
  core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelVersionMetaService.java
Labels: branch-0.9

#7014 [#7011] improve (core): Add object type of AssociateTagsForMetadataObjectEvent
  core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectFailureEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectPreEvent.java
  core/src/test/java/org/apache/gravitino/listener/api/event/TestTagEvent.java
Labels: branch-0.9

#6985 [#6981] feat(credential): support specifying location when get fileset credential
  catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
  catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectCredentialOperations.java
  clients/client-python/gravitino/api/credential/credential.py
  clients/client-python/gravitino/client/metadata_object_credential_operations.py
  clients/client-python/gravitino/filesystem/gvfs_base_operations.py
  clients/client-python/gravitino/filesystem/gvfs_config.py
  clients/client-python/tests/integration/test_gvfs_with_abs_credential.py
  clients/client-python/tests/integration/test_gvfs_with_gcs_credential.py
  clients/client-python/tests/integration/test_gvfs_with_oss_credential.py
  clients/client-python/tests/integration/test_gvfs_with_s3_credential.py
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/BaseGVFSOperations.java
  clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/FilesetCatalogCredentialIT.java
  docs/hadoop-catalog-with-adls.md
  docs/hadoop-catalog-with-gcs.md
  docs/hadoop-catalog-with-oss.md
  docs/hadoop-catalog-with-s3.md
  docs/how-to-use-gvfs.md
  server-common/build.gradle.kts
  server-common/src/main/java/org/apache/gravitino/server/web/Utils.java
  server/src/main/java/org/apache/gravitino/server/web/rest/MetadataObjectCredentialOperations.java
Labels: branch-0.9

#7022 [#7020] improvement(build): Update rust module in the release script
  dev/release/release-tag.sh
Labels: branch-0.8, branch-0.9

#7030 [#7029] improvement(version): version parse supports complex suffix
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java
  clients/client-python/tests/unittests/test_gravitino_version.py
Labels: branch-0.9

#7009 [#6936] improvement(doc): update doc for fileset multiple locations
  docs/hadoop-catalog.md
  docs/how-to-use-gvfs.md
  docs/manage-fileset-metadata-using-gravitino.md
Labels: branch-0.9

#6921 [#6920] docs(docs): Add doc to Model update
  docs/gravitino-server-config.md
  docs/manage-model-metadata-using-gravitino.md
  docs/open-api/models.yaml
Labels: branch-0.9

#6946 [#6946] docs(lineage): add lineage document
  docs/lineage/gravitino-server-lineage.md
  docs/lineage/gravitino-spark-lineage.md
  docs/lineage/lineage.md
Labels: branch-0.9

#7039 [#6647] docs(iceberg): add Iceberg cloud package information to credential vending document
  docs/security/credential-vending.md
Labels: branch-0.9

#6977 [#6974] openapi(lineage): add Lineage openapi
  docs/open-api/lineage.yaml
  docs/open-api/openapi.yaml
Labels: branch-0.9

#7041 [#6525] feature(core): Support update comment operations for model alteration.
  api/src/main/java/org/apache/gravitino/model/ModelChange.java
  api/src/test/java/org/apache/gravitino/model/TestModelChange.java
  catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
  catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
  catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
  clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
  clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
  clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelComment.java
  clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
  clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
  clients/client-python/gravitino/api/model_change.py
  clients/client-python/gravitino/client/generic_model_catalog.py
  clients/client-python/gravitino/dto/requests/model_update_request.py
  clients/client-python/tests/integration/test_model_catalog.py
  common/src/main/java/org/apache/gravitino/dto/requests/ModelUpdateRequest.java
  core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
  core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
  core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelMetaService.java
  docs/manage-model-metadata-using-gravitino.md
Labels: branch-0.9

#7049 [MINOR] docs(docs): Update models.yaml
  docs/open-api/models.yaml
Labels: branch-0.9

#7001 [#6917] test(authz): Add more test cases about Hdfs Ranger authz plugin
  authorizations/authorization-chain/src/test/java/org/apache/gravitino/authorization/chain/integration/test/TestChainedAuthorizationIT.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java
  authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationHDFSPluginIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerFilesetIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveHdfsE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java
  authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerPaimonE2EIT.java
Labels: branch-0.9

#7050 [#6544] improvement(catalog): support hyphen in catalog name
  catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
  core/src/main/java/org/apache/gravitino/catalog/CatalogNormalizeDispatcher.java
  core/src/test/java/org/apache/gravitino/catalog/TestCatalogNormalizeDispatcher.java
Labels: branch-0.9

#7056 [#7054] fix(build): Fail to build Iceberg REST catalog Docker image
  build.gradle.kts
Labels: branch-0.9

#7059 [MINOR] fix(docs): Fix typo of `spark-integration-test.md`
  docs/spark-connector/spark-integration-test.md
Labels: branch-0.9

#6978 [#6845] fix(core): handle NonEmptyEntityException while dropSchema
  catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
  core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java
Labels: branch-0.9

#7069 [#7066] fix(build): Update chart version in the release script
  dev/release/release-tag.sh
Labels: branch-0.9

#7070 [#7068] fix unexpected output in gravitino-server.out
  conf/log4j2.properties.template
Labels: branch-0.9

#6980 [#6513] fix resource leak in BaseCatalog
  core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
Labels: branch-0.9

#7083 [MINOR] docs: Change doc for chart.md
  docs/chart.md
  docs/how-to-install.md
Labels: branch-0.9

#7092 [#7091] fix(docs): Fix the errors of the document
  docs/flink-connector/flink-catalog-jdbc.md
  docs/manage-fileset-metadata-using-gravitino.md
Labels: branch-0.9

#7076 [#7046] fix(spark-connector): Spark connector fails to parse timestamp data type
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/hive/SparkHiveTypeConverter.java
  spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/hive/SparkHiveCatalogIT.java
  spark-connector/v3.4/spark/src/main/java/org/apache/gravitino/spark/connector/hive/GravitinoHiveCatalogSpark34.java
  spark-connector/v3.4/spark/src/main/java/org/apache/gravitino/spark/connector/hive/SparkHiveTypeConverter34.java
  spark-connector/v3.4/spark/src/test/java/org/apache/gravitino/spark/connector/TestSparkHiveTypeConverter34.java
Labels: branch-0.9

#7088 [MINOR] feat(license): add OpenLineage license
  LICENSE
  NOTICE.bin
  build.gradle.kts
  docs/open-api/lineage.yaml
  lineage/src/test/java/org/apache/gravitino/lineage/source/TestLineageOperations.java
Labels: branch-0.9

#7090 [#7087] fix(license): Fix the licenses issues
  LICENSE
  NOTICE
  core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionFailureEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionPreEvent.java
  core/src/main/java/org/apache/gravitino/listener/api/info/Either.java
  core/src/test/java/org/apache/gravitino/listener/api/event/TestEither.java
  dev/ci/chart_schema.yaml
  dev/ci/lintconf.yaml
  web/web/LICENSE.bin
  web/web/licenses/call-bind-apply-helpers.txt
  web/web/licenses/call-bound.txt
  web/web/licenses/dunder-proto.txt
  web/web/licenses/fast-color.txt
  web/web/licenses/get-proto.txt
  web/web/licenses/math-intrinstics.txt
Labels: branch-0.9
