Repository apache/gravitino, pull requests merged in 2025-09, with the labels that each got.

#8389 [#4707] fix (client): Fix the Gravitino client-side version verification to ignore patch version numbers
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java
  clients/client-python/gravitino/client/gravitino_client_base.py
  clients/client-python/gravitino/client/gravitino_version.py
  clients/client-python/tests/unittests/test_gravitino_version.py
Labels: branch-0.8, branch-0.9

#8392 [#8391] fix(docs): Fix error in documents about how to use bundle jars for Azure Blob Storage and GCS
  docs/fileset-catalog-with-adls.md
  docs/fileset-catalog-with-gcs.md
Labels: branch-0.9

#8336 [#8335] fix(client): Fix double encoding issue and add missing URL encoding
  clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
  clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java
  clients/client-java/src/main/java/org/apache/gravitino/client/HTTPClient.java
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectCredentialOperations.java
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectRoleOperations.java
  clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
  clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java
  clients/client-python/gravitino/client/fileset_catalog.py
  clients/client-python/gravitino/client/generic_model_catalog.py
  clients/client-python/gravitino/client/gravitino_client_base.py
  clients/client-python/gravitino/client/gravitino_metalake.py
  clients/client-python/gravitino/client/metadata_object_credential_operations.py
  clients/client-python/gravitino/filesystem/gvfs_base_operations.py
  clients/client-python/tests/unittests/test_gravitino_client.py
  clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
  common/src/main/java/org/apache/gravitino/Version.java
  common/src/main/java/org/apache/gravitino/rest/RESTUtils.java
  server-common/src/main/java/org/apache/gravitino/server/web/Utils.java
  server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java
  server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
Labels: branch-1.0

#8413 [MINOR] improve(CI): Increase the CI timeout for Python and Ranger test
  .github/workflows/access-control-integration-test.yml
  .github/workflows/python-integration-test.yml
Labels: branch-0.9, branch-1.0

#8407 [#8380] fix: Fix test in TestPartitionRange
  api/src/test/java/org/apache/gravitino/stats/TestPartitionRange.java
Labels: branch-1.0

#8373 [#7159] feat(helm): Support configurations for Iceberg REST server in Gravitino helm chart
  dev/charts/gravitino-iceberg-rest-server/Chart.yaml
  dev/charts/gravitino-iceberg-rest-server/resources/gravitino-iceberg-rest-server.conf
  dev/charts/gravitino-iceberg-rest-server/templates/tests/test-connection.yaml
  dev/charts/gravitino-iceberg-rest-server/values.yaml
  dev/charts/gravitino/Chart.yaml
  dev/charts/gravitino/resources/config/gravitino.conf
  dev/charts/gravitino/values.yaml
Labels: branch-1.0

#8363 [#5199] feat(client-python): add partitioning DTO serdes
  clients/client-python/gravitino/api/types/json_serdes/base.py
  clients/client-python/gravitino/dto/rel/partitioning/json_serdes/__init__.py
  clients/client-python/gravitino/dto/rel/partitioning/json_serdes/partitioning_serdes.py
  clients/client-python/gravitino/dto/rel/partitioning/partitioning.py
  clients/client-python/gravitino/utils/serdes.py
  clients/client-python/tests/unittests/dto/rel/test_partitioning_serdes.py
Labels: branch-1.0

#8240 [#8218] fix(doris): Fix BUCKETS AUTO parsing for RANDOM distribution
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisExceptionConverter.java
  catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/utils/DorisUtils.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/converter/TestDorisExceptionConverter.java
  catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/utils/TestDorisUtils.java
Labels: branch-1.0

#8357 [#8041][#8337][#8353] fix (server): Fix class conflicts in the AWS bundle JARs and other bundle JARs.
  bundles/aliyun/build.gradle.kts
  bundles/aws/build.gradle.kts
  bundles/azure/build.gradle.kts
  bundles/gcp/build.gradle.kts
  catalogs/catalog-common/build.gradle.kts
  gradle/libs.versions.toml
Labels: branch-1.0

#8437 [#8435] feat(iceberg): passing s3.path-style-access to the client side in Iceberg REST server
  iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/CatalogWrapperForREST.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/IcebergRestTestUtil.java
  iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java
Labels: branch-1.0

#8216 [#8215] connector(trino/flink): Support for reading/writing time precision
  flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/TypeUtils.java
  flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
  trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.txt
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLDataTypeTransformer.java
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/util/GeneralDataTypeTransformer.java
  trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/util/TestDataTypeTransformer.java
Labels: branch-1.0

#8297 [#7804][#7797][#8155][#8181][#8182][#7787] fix(cache): Fix metadata cache data consistency error
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/PolicyIT.java
  clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/MetadataObjectRoleAuthorizationIT.java
  core/src/jcstress/java/org/apache/gravitino/cache/TestCacheIndexCoherence.java
  core/src/main/java/org/apache/gravitino/cache/CaffeineEntityCache.java
  core/src/main/java/org/apache/gravitino/cache/EntityCacheKey.java
  core/src/main/java/org/apache/gravitino/cache/EntityCacheRelationKey.java
  core/src/main/java/org/apache/gravitino/cache/ReverseIndexCache.java
  core/src/main/java/org/apache/gravitino/cache/ReverseIndexRules.java
  core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java
  core/src/test/java/org/apache/gravitino/cache/TestCacheIndex.java
  core/src/test/java/org/apache/gravitino/cache/TestCaffeineEntityCache.java
  core/src/test/java/org/apache/gravitino/cache/TestEntityCacheKey.java
  core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
  core/src/test/java/org/apache/gravitino/utils/TestUtil.java
Labels: branch-1.0

#8461 [MINOR] fix(test): Disable `_catalog_cache.clear` when cache is diabled.
  clients/client-python/tests/integration/test_gvfs_with_s3.py
Labels: branch-1.0

#8432 [#8431] improvement(bundles): Remove unnecessary relocate in fileset bundle jars.
  bundles/aliyun/build.gradle.kts
  bundles/azure-bundle/build.gradle.kts
  bundles/azure/build.gradle.kts
  bundles/gcp-bundle/build.gradle.kts
  bundles/gcp/build.gradle.kts
  docs/fileset-catalog-with-adls.md
  docs/fileset-catalog-with-gcs.md
  docs/fileset-catalog-with-oss.md
  docs/fileset-catalog-with-s3.md
Labels: branch-1.0

#8478 [MINOR] fix(release): Fix the release script issue
  dev/release/release-tag.sh
  mcp-server/pyproject.toml
Labels: branch-1.0

#8490 [#8486] Improvement(core): Correct the LocalJobExecutor test teardown to run after each test
  core/src/test/java/org/apache/gravitino/job/local/TestLocalJobExecutor.java
Labels: branch-1.0

#8443 [#8339] feat(authz): map GROUP to GroupEntity in MetadataIdConverter; add unit test
  server-common/src/main/java/org/apache/gravitino/server/authorization/MetadataIdConverter.java
  server-common/src/test/java/org/apache/gravitino/server/authorization/TestMetadataIdConverter.java
Labels: branch-1.0

#8493 [#8484] Improvement(trino):JDBCCatalogPropertyConverter.java converter where the required property set mistakenly includes the password key twice
  trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/JDBCCatalogPropertyConverter.java
  trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/jdbc/TestJDBCCatalogPropertyConverter.java
Labels: branch-1.0

#8213 [#8163] feat(catalog): Support paimon latest version-1.2.0
  build.gradle.kts
  catalogs/catalog-lakehouse-paimon/build.gradle.kts
  catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/ops/PaimonCatalogOps.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonFileSystemIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonHiveIT.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/ops/TestPaimonCatalogOps.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestCatalogUtils.java
  catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestTableOpsUtils.java
  docs/lakehouse-paimon-catalog.md
  docs/spark-connector/spark-catalog-iceberg.md
  docs/spark-connector/spark-catalog-jdbc.md
  docs/spark-connector/spark-catalog-paimon.md
  docs/spark-connector/spark-connector.md
  gradle/libs.versions.toml
  spark-connector/spark-common/build.gradle.kts
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/GravitinoSparkConfig.java
  spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java
  spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/SparkEnvIT.java
  spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/sql/SparkQueryRunner.java
  spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/util/SparkTableInfo.java
  spark-connector/v3.3/spark/build.gradle.kts
  spark-connector/v3.3/spark/src/test/java/org/apache/gravitino/spark/connector/version/TestCatalogNameAdaptor.java
  spark-connector/v3.4/spark/build.gradle.kts
  spark-connector/v3.4/spark/src/test/java/org/apache/gravitino/spark/connector/version/TestCatalogNameAdaptor.java
  spark-connector/v3.5/spark/build.gradle.kts
  spark-connector/v3.5/spark/src/test/java/org/apache/gravitino/spark/connector/version/TestCatalogNameAdaptor.java
Labels: branch-1.0

#8560 [#8558] fix(metrics): fix missing backend connection pool metrics
  core/src/main/java/org/apache/gravitino/metrics/MetricNames.java
  core/src/main/java/org/apache/gravitino/metrics/MetricsSystem.java
  core/src/main/java/org/apache/gravitino/metrics/source/MetricsSource.java
  core/src/main/java/org/apache/gravitino/metrics/source/RelationDatasourceMetricsSource.java
  core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
  core/src/test/java/org/apache/gravitino/metrics/TestExtractMetricNameAndLabel.java
  core/src/test/java/org/apache/gravitino/metrics/TestMetricsSystem.java
Labels: branch-1.0

#8599 [#8597] Fix image not found
  dev/charts/gravitino/Chart.yaml
  dev/charts/gravitino/values.yaml
Labels: branch-1.0

#8600 [MINOR] docs(mcp): polish MCP server document
  docs/gravitino-mcp-server.md
  mcp-server/mcp_server/core/context.py
  mcp-server/mcp_server/core/setting.py
  mcp-server/mcp_server/main.py
Labels: branch-1.0

#8607 [#7962]feat(core): Add spark process builder support for local job executor
  api/src/main/java/org/apache/gravitino/job/SparkJobTemplate.java
  common/src/main/java/org/apache/gravitino/dto/job/SparkJobTemplateDTO.java
  common/src/test/java/org/apache/gravitino/dto/job/TestJobTemplateDTO.java
  core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutorConfigs.java
  core/src/main/java/org/apache/gravitino/job/local/LocalProcessBuilder.java
  core/src/main/java/org/apache/gravitino/job/local/ShellProcessBuilder.java
  core/src/main/java/org/apache/gravitino/job/local/SparkProcessBuilder.java
  core/src/test/java/org/apache/gravitino/job/local/TestSparkProcessBuilder.java
  docs/manage-jobs-in-gravitino.md
Labels: branch-1.0

#8654 [MINOR] fix(docs): Fix JDK description error in docs
  docs/index.md
Labels: branch-1.0

#8643 [#8550]The init.sh is configurable in values.yaml and monitor configmap.yaml changes
  dev/charts/gravitino-iceberg-rest-server/resources/init.sh
  dev/charts/gravitino-iceberg-rest-server/templates/configmap.yaml
  dev/charts/gravitino-iceberg-rest-server/templates/deployment.yaml
  dev/charts/gravitino-iceberg-rest-server/values.yaml
  dev/charts/gravitino/resources/config/init.sh
  dev/charts/gravitino/templates/configmap.yaml
  dev/charts/gravitino/templates/deployment.yaml
  dev/charts/gravitino/values.yaml
Labels: branch-1.0

#8686 [#8664] improvement(core): add missing space between the table name and column list in insertModelMetaOnDuplicateKeyUpdate query
  core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/ModelMetaPostgreSQLProvider.java
Labels: branch-1.0

#8644 [#8638] feat(api): Add Java and Python interface for job template alteration
  api/src/main/java/org/apache/gravitino/job/JobTemplateChange.java
  api/src/main/java/org/apache/gravitino/job/SupportsJobs.java
  api/src/test/java/org/apache/gravitino/job/TestJobTemplateChange.java
  clients/client-python/gravitino/api/job/job_template_change.py
  clients/client-python/gravitino/api/job/supports_jobs.py
  clients/client-python/tests/unittests/job/__init__.py
  clients/client-python/tests/unittests/job/test_job_template_change.py
  core/src/main/java/org/apache/gravitino/job/JobManager.java
  core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutor.java
Labels: branch-1.0

#8701 [#8655] fix(api): Add null check for comparator in PartitionRange
  api/src/main/java/org/apache/gravitino/stats/PartitionRange.java
  api/src/test/java/org/apache/gravitino/stats/TestPartitionRange.java
Labels: branch-1.0

#8711 [MINOR] fix(docs): Fix the statistics list response
  docs/open-api/statistics.yaml
Labels: branch-1.0

#8698 [#8697] improvement(core): Adjust weight value for entities with type `metalake` and `catalog` in Caffeine cache weighter.
  core/src/main/java/org/apache/gravitino/cache/EntityCacheWeigher.java
  core/src/test/java/org/apache/gravitino/cache/TestCacheConfig.java
Labels: branch-1.0

#8717 [#4168] fix(kafka-catalog): make topic creation synchronous
  catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogOperations.java
Labels: branch-1.0

#8734 [#8731] fix(policy): PolicyUpdateRequest.validate checks for null policyType
  common/src/main/java/org/apache/gravitino/dto/requests/PolicyUpdateRequest.java
Labels: branch-1.0
